export type PriorityPageBoost = {
  eyebrow: string;
  title: string;
  description: string;
  links: Array<[string, string, string]>;
};

const b = (eyebrow: string, title: string, description: string, links: Array<[string, string, string]>): PriorityPageBoost => ({ eyebrow, title, description, links });

export const PRIORITY_PAGES_31_100: Record<string, PriorityPageBoost> = {
  '/trabajo': b('Elegí tu situación', '¿Qué necesitás resolver de tu trabajo?', 'Entrá por el problema concreto y llegá directo a la cuenta y la explicación que corresponde.', [['/trabajo/sueldo-bruto-y-neto','Entender mi sueldo','Bruto, descuentos y neto.'],['/trabajo/liquidacion-final','Terminé de trabajar','Renuncia, despido y liquidación.'],['/trabajo/vacaciones','Calcular vacaciones','Días, plus y saldo pendiente.']]),
  '/feriados-chile-2026': b('Planificá el año', 'Próximos feriados y fines de semana largos', 'Revisá qué fecha te sirve y seguí con la cuenta necesaria para organizar viaje, descanso o trabajo.', [['/cl/trabajo','¿Se trabaja o se paga extra?','Jornada y recargos en Chile.'],['/viajes/presupuesto-de-viaje','Armar un presupuesto','Transporte, alojamiento y gastos.'],['/dias-entre-dos-fechas','Contar días exactos','Laborables y corridos.']]),
  '/mi-hacecuentas': b('Tu espacio', 'Guardá tus cuentas y retomá donde dejaste', 'Usá favoritos y datos habituales para evitar cargar lo mismo cada vez. Todo queda en este dispositivo.', [['/buscar','Encontrar una calculadora','Buscá por problema o palabra.'],['/populares','Ver las más usadas','Atajos a las herramientas principales.'],['/alertas','Recibir cambios importantes','Fechas, topes y valores.']]),
  '/tecnologia/resistencias': b('Del código al circuito', 'Comprobá el valor antes de soldar', 'Convertí bandas a ohmios, revisá tolerancia y seguí con los cálculos eléctricos relacionados.', [['/tecnologia/instalacion-electrica','Dimensionar cable y protección','Corriente, sección y térmica.'],['/tecnologia/baterias','Calcular autonomía','Capacidad, consumo y duración.'],['/tecnologia','Más herramientas técnicas','Electrónica, energía y proyectos.']]),
  '/fechas/generaciones': b('Poné el año en contexto', '¿A qué generación pertenece cada persona?', 'Compará años de nacimiento sin perder de vista que los límites son aproximados y varían según la fuente.', [['/fechas/edad-exacta','Calcular edad exacta','Años, meses y días.'],['/dias-entre-dos-fechas','Medir un período','Días corridos y laborables.'],['/fechas','Más cuentas de fechas','Calendarios, plazos y edades.']]),
  '/tecnologia/impresion-3d': b('Antes de imprimir', 'Costo, tiempo y material de la pieza', 'Separá filamento, energía, fallas y amortización para cotizar sin vender por debajo del costo.', [['/negocios/precio-de-venta','Definir precio de venta','Costo, margen y markup.'],['/tecnologia/almacenamiento','Calcular archivos y capacidad','Bytes, MB, GB y TB.'],['/tecnologia','Más herramientas técnicas','Proyectos y fabricación.']]),
  '/mx/trabajo/finiquito-y-liquidacion': b('México · relación laboral', 'Renuncia, finiquito o liquidación: elegí el caso', 'La causa de salida cambia los conceptos. Revisá primero el escenario y después completá salario y antigüedad.', [['/mx/trabajo/sueldo-neto','Revisar mi sueldo neto','ISR, IMSS y descuentos.'],['/mx/trabajo/aguinaldo-prima-y-ptu','Prestaciones pendientes','Aguinaldo, prima y PTU.'],['/mx/trabajo','Todas las cuentas laborales','Trabajo en México.']]),
  '/futbol/mundial-2026': b('Archivo del Mundial 2026', 'Resultados, estadísticas y cuentas que dejó el torneo', 'Consultá el torneo cerrado y pasá a las herramientas vigentes sin depender de módulos temporales.', [['/futbol-hoy','Fútbol de hoy','Partidos y contexto actual.'],['/deportes','Más herramientas deportivas','Rendimiento, tablas y torneos.'],['/calculadora','Explorar calculadoras','Todo el catálogo.']]),
  '/py/trabajo/sueldo-neto': b('Paraguay · salario vigente', 'Del salario mínimo al monto que cobrás', 'Compará mensual, jornal y hora; después aplicá el descuento del IPS para estimar el neto.', [['/py/trabajo/ips','Calcular aporte IPS','Aporte obrero y patronal.'],['/py/trabajo/liquidacion-final','Calcular liquidación','Aguinaldo, vacaciones e indemnización.'],['/py/trabajo','Trabajo en Paraguay','Todas las herramientas.']]),
  '/recategorizacion-monotributo-julio-2026': b('Después del vencimiento', 'Qué hacer si no te recategorizaste a tiempo', 'Revisá la categoría actual, comparala con tus últimos 12 meses y verificá si ARCA hizo una recategorización de oficio.', [['/impuestos/monotributo','Calcular mi categoría','Escala y cuota vigente.'],['/datos-monotributo-2026','Ver la tabla completa','Topes y cuotas por categoría.'],['/impuestos','Más impuestos','Ganancias, IVA y Bienes Personales.']]),
  '/nutricion/calorias-diarias': b('Convertí el resultado en un plan', 'Mantenimiento, déficit o superávit', 'Usá tus calorías como punto de partida y conectalas con composición corporal y distribución de macros.', [['/salud/grasa-corporal','Medir composición corporal','Grasa, masa magra y FFMI.'],['/salud/macros','Distribuir proteínas y macros','Gramos diarios por objetivo.'],['/salud/peso-ideal-imc','Revisar peso e IMC','Rango saludable y seguimiento.']]),
  '/co/validar-nit': b('Colombia · verificación', 'NIT, RUT y dígito de verificación no son lo mismo', 'Validá el formato y seguí con el trámite o impuesto que corresponda a tu actividad.', [['/co/impuestos/impuestos-de-mi-negocio','Impuestos de mi negocio','Renta, IVA e ICA.'],['/co/impuestos/retencion-en-la-fuente','Calcular retenciones','Base y tarifa aplicable.'],['/co/calculadoras','Más herramientas Colombia','Catálogo local.']]),
  '/embarazo/semanas': b('Tu embarazo en una sola línea de tiempo', 'Semana, trimestre, fecha probable e hitos', 'Partí de la FUM o la fecha clínica disponible y usá siempre la indicación profesional como referencia principal.', [['/embarazo/fecha-de-parto','Calcular fecha probable','FUM, concepción o ecografía.'],['/salud/peso-en-el-embarazo','Seguir aumento de peso','Rango orientativo por semana.'],['/embarazo','Más herramientas de embarazo','Calendarios y seguimiento.']]),
  '/matematica/porcentajes': b('Elegí la cuenta correcta', 'Aumento, descuento, variación o porcentaje inverso', 'El mismo símbolo % responde preguntas distintas. Elegí el caso antes de cargar los números.', [['/matematica/regla-de-tres','Resolver una proporción','Directa, inversa o compuesta.'],['/matematica','Más herramientas matemáticas','Cuentas cotidianas y estudio.'],['/calculadora-cientifica','Usar calculadora científica','Potencias, raíces y funciones.']]),
  '/inversiones/plazo-fijo': b('No mires sólo la TNA', 'Compará rendimiento, inflación y disponibilidad', 'Calculá cuánto cobrás, cuánto ganás en términos reales y qué cambia si renovás el capital.', [['/inversiones/interes-compuesto','Simular reinversión','Capital, aportes y tasa.'],['/finanzas-personales/dolar','Comparar con dólar','Oficial, MEP, CCL y blue.'],['/valores-bcra','Ver tasas vigentes','Datos financieros actualizados.']]),
  '/auto/tramites': b('El costo cambia según el trámite', 'Transferencia, patente o VTV', 'Elegí provincia, tipo de vehículo y gestión para no mezclar aranceles que se calculan de forma distinta.', [['/auto/costo-anual','Costo anual del auto','Seguro, patente y mantenimiento.'],['/auto/nafta-y-peajes','Costo del viaje','Combustible, peajes y pasajeros.'],['/auto','Todas las cuentas del auto','Compra, uso y trámites.']]),
  '/co/impuestos/renta-personas': b('Colombia · renta personal', 'Primero: ¿declarás? Después: ¿cuánto pagás?', 'Separá obligación de declarar, renta líquida, deducciones, UVT y retenciones ya practicadas.', [['/co/impuestos/retencion-en-la-fuente','Revisar retenciones','Salario y otros pagos.'],['/co/impuestos/patrimonio-y-herencia','Patrimonio y herencia','Bienes y obligaciones.'],['/co/impuestos','Impuestos Colombia','Todas las herramientas.']]),
  '/trabajo/sueldo-bruto-y-neto': b('Leé tu recibo', 'Del bruto al bolsillo —o del neto al bruto', 'Compará aportes, obra social y Ganancias, y detectá qué concepto explica la diferencia.', [['/impuestos/ganancias-cuarta-categoria','Calcular Ganancias','Retención y deducciones.'],['/trabajo/sueldo-vs-inflacion','Medir poder de compra','Sueldo real contra IPC.'],['/trabajo/sueldos-por-convenio','Ver básico de convenio','Categoría y antigüedad.']]),
  '/construccion/costo-por-m2': b('Presupuesto por etapas', 'Materiales, mano de obra e imprevistos', 'Usá el costo por m² como rango y bajalo después a cantidades concretas para cada rubro.', [['/construccion/ladrillos','Calcular mampostería','Ladrillos y desperdicio.'],['/construccion/pintura','Calcular pintura','Superficie, manos y litros.'],['/construccion/hormigon','Calcular hormigón','Volumen y materiales.']]),
  '/pe/auto/costos-del-auto': b('Perú · costo vehicular', 'SOAT, revisión, impuesto y combustible', 'Separá gastos obligatorios de uso para conocer el costo anual real de tener el vehículo.', [['/pe/auto','Todas las cuentas del auto','Costos y decisiones.'],['/auto/nafta-y-peajes','Presupuestar un viaje','Combustible y peajes.'],['/pe/calculadoras','Más herramientas Perú','Catálogo local.']]),
  '/datos-bienes-personales-2026': b('Datos fiscales 2026', 'Mínimo, casa-habitación y escala en contexto', 'Usá la tabla como referencia y pasá al simulador para considerar bienes exentos, ubicación y situación personal.', [['/impuestos/bienes-personales','Simular Bienes Personales','Patrimonio y escala.'],['/impuestos','Más impuestos Argentina','Ganancias, IVA y Monotributo.'],['/datasets','Descargar datos','Fuentes y formatos reutilizables.']]),
  '/finanzas-personales/salir-de-deudas': b('Ordená antes de pagar', 'Capital, tasa, mora y prioridad', 'Separá deuda financiera de actualización judicial y elegí la estrategia según costo y urgencia.', [['/finanzas-personales/prestamo','Comparar préstamos','Cuota, CFT y sistemas.'],['/finanzas-personales/gastos-del-mes','Ordenar presupuesto','Ingresos, gastos y saldo.'],['/finanzas-personales','Más finanzas personales','Ahorro, crédito y deudas.']]),
  '/trabajo/liquidacion-final': b('Elegí cómo terminó la relación', 'Renuncia, despido o casas particulares', 'La causa y el régimen cambian indemnización, preaviso, vacaciones y SAC proporcional.', [['/trabajo/indemnizacion-por-despido','Calcular indemnización','Antigüedad y topes.'],['/trabajo/vacaciones','Calcular vacaciones pendientes','Días y plus vacacional.'],['/trabajo/aguinaldo','Calcular SAC proporcional','Mejor remuneración y tiempo.']]),
  '/trabajo/costo-de-un-empleado': b('Costo empresa', 'Del sueldo bruto al costo anual total', 'Sumá contribuciones, ART, SAC, vacaciones y beneficios para evitar mirar sólo el salario mensual.', [['/trabajo/sueldo-bruto-y-neto','Ver el lado del empleado','Aportes y salario neto.'],['/trabajo/empleada-domestica','Casas particulares','Escala y aportes.'],['/trabajo','Más cuentas laborales','Contratación y liquidación.']]),
  '/py/finanzas/guaranies': b('Paraguay · conversión', 'Guaraníes, pesos y dólares con referencia visible', 'Revisá moneda de origen, compra/venta y momento de la cotización antes de comparar.', [['/cambio-de-monedas','Cotizaciones en vivo','Dólar y monedas regionales.'],['/py/finanzas','Finanzas Paraguay','Presupuesto, ahorro y viajes.'],['/py/calculadoras','Más herramientas Paraguay','Catálogo local.']]),
  '/eventos/bebidas': b('Que alcance sin comprar de más', 'Bebidas, hielo y margen de seguridad', 'Ajustá por cantidad de invitados, duración, clima y proporción de personas que toman alcohol.', [['/eventos/comida','Calcular comida','Porciones por invitado.'],['/eventos/logistica','Mesas, sillas y personal','Logística del evento.'],['/calculadoras-evento','Planificar todo el evento','Presupuesto y cantidades.']]),
  '/co/trabajo/costo-de-contratar': b('Colombia · costo empresa', 'Salario, seguridad social, ARL y prestaciones', 'Elegí la clase de riesgo y mirá el costo mensual y anual completo para empleador y trabajador.', [['/co/trabajo/sueldo-neto','Calcular sueldo neto','Aportes y salario de bolsillo.'],['/co/trabajo/horas-extras-y-recargos','Agregar horas y recargos','Jornada de 42 horas.'],['/co/trabajo','Más herramientas laborales','Trabajo en Colombia.']]),
  '/conversores/numeros-a-letras': b('Listo para copiar', 'Importes, centavos y formatos habituales', 'Convertí el número y elegí si lo necesitás para cheque, pagaré, factura, romano o binario.', [['/conversores','Más conversores','Medidas, peso y temperatura.'],['/validar-cbu','Validar CBU','Controlar datos bancarios.'],['/validar-cuit','Validar CUIT','Formato y dígito verificador.']]),
  '/feriados-colombia-2026': b('Colombia · calendario', 'Próximos festivos y puentes de 2026', 'Identificá los trasladables por Ley Emiliani y calculá días de descanso o recargos laborales.', [['/co/trabajo/horas-extras-y-recargos','Calcular recargo festivo','Jornada y recargos.'],['/dias-entre-dos-fechas','Contar días','Corridos y laborables.'],['/co/calculadoras','Más herramientas Colombia','Catálogo local.']]),
  '/trabajo/seguro-de-desempleo': b('ANSES · desempleo', 'Monto, duración y próximos pasos', 'Revisá requisitos, meses cotizados y documentación antes de estimar la prestación.', [['/trabajo/liquidacion-final','Calcular liquidación','Conceptos de la desvinculación.'],['/trabajo/indemnizacion-por-despido','Calcular indemnización','Antigüedad y topes.'],['/trabajo','Más herramientas laborales','Sueldo y derechos.']]),
  '/trabajo/sueldos-por-convenio': b('Buscá por actividad', 'Convenio, categoría, zona y antigüedad', 'El básico no siempre coincide con el bruto: agregá adicionales y verificá la fecha de la última escala.', [['/trabajo/sueldo-bruto-y-neto','Pasar a sueldo neto','Aportes y descuentos.'],['/trabajo/horas-extra','Agregar horas extra','Valor hora y recargos.'],['/trabajo','Más cuentas laborales','Sueldo y liquidación.']]),
  '/inversiones/interes-compuesto': b('Probá más de un escenario', 'Capital, aportes, tasa y tiempo', 'Compará una tasa optimista, una conservadora y el efecto de aportar todos los meses.', [['/inversiones/plazo-fijo','Simular plazo fijo','Tasa y renovación.'],['/finanzas-personales/meta-de-ahorro','Definir una meta','Monto, plazo y aporte necesario.'],['/finanzas-personales','Más finanzas personales','Ahorro e inversión.']]),
  '/impuestos/retenciones': b('Argentina · RG 830', 'Base, mínimo y condición fiscal', 'Revisá el concepto pagado, la acumulación del mes y la constancia antes de aplicar la alícuota.', [['/impuestos/ganancias-cuarta-categoria','Ganancias del sueldo','Retención y deducciones.'],['/impuestos/monotributo','Monotributo','Categoría y cuota.'],['/impuestos','Más impuestos','Herramientas fiscales.']]),
  '/mascotas/edad-del-gato': b('Edad y etapa de vida', 'De años felinos a cuidados concretos', 'La equivalencia es orientativa: usala para ubicar la etapa y revisar controles, alimentación y peso.', [['/mascotas','Más herramientas de mascotas','Edad, salud y costos.'],['/salud/habitos','Seguimiento de hábitos','Rutinas y objetivos.'],['/calculadora','Explorar calculadoras','Todo el catálogo.']]),
  '/co/finanzas/comprar-vivienda': b('Colombia · comprar vivienda', 'Precio, escritura, registro y financiación', 'Separá gastos del comprador y vendedor y sumalos al ahorro inicial antes de elegir crédito.', [['/co/finanzas/creditos-y-tarjetas','Comparar financiación','Cuota y capacidad de pago.'],['/co/finanzas','Más finanzas Colombia','Crédito, ahorro y vivienda.'],['/co/calculadoras','Catálogo Colombia','Todas las herramientas.']]),
  '/valores-bcra': b('Datos vigentes', 'Tasas, dólar e índices con fecha visible', 'Tomá cada valor con su fecha de referencia y entrá a la calculadora que lo usa para interpretar el impacto.', [['/inversiones/plazo-fijo','Simular plazo fijo','Aplicar una tasa.'],['/finanzas-personales/dolar','Comparar dólares','Oficial, MEP, CCL y blue.'],['/datasets','Descargar datos','JSON, CSV y fuentes.']]),
  '/co/impuestos/impuestos-de-mi-negocio': b('Colombia · negocio', 'Renta, IVA, ICA y retenciones', 'Elegí actividad y municipio para separar obligaciones nacionales de impuestos territoriales.', [['/co/impuestos/retencion-en-la-fuente','Calcular retención','Base y tarifa.'],['/co/validar-nit','Validar NIT','Formato y dígito.'],['/co/impuestos','Más impuestos Colombia','Todas las herramientas.']]),
  '/vivienda/gastos-de-escritura': b('Argentina · compraventa', 'Quién paga cada gasto y cuánto reservar', 'Calculá por provincia, tipo de inmueble y lado de la operación: comprador o vendedor.', [['/vivienda/credito-hipotecario','Simular crédito','Cuota y sistemas.'],['/vivienda/rentabilidad-de-un-alquiler','Medir rentabilidad','Ingreso, gastos y retorno.'],['/vivienda','Más cuentas de vivienda','Comprar, vender y alquilar.']]),
  '/embarazo/fecha-de-parto': b('Tres formas de estimarla', 'FUM, concepción o ecografía', 'El resultado es un rango probable; la fecha clínica indicada por el equipo de salud tiene prioridad.', [['/embarazo/semanas','Ver semana actual','Trimestre e hitos.'],['/salud/peso-en-el-embarazo','Seguir aumento de peso','Rango por semana.'],['/embarazo','Más herramientas de embarazo','Calendarios y seguimiento.']]),
  '/trabajo/vacaciones': b('Argentina · vacaciones', 'Días, plus y saldo pendiente', 'Usá fecha de ingreso y sueldo habitual; separá días legales de vacaciones no gozadas en una liquidación.', [['/trabajo/liquidacion-final','Vacaciones en liquidación','Renuncia o despido.'],['/trabajo/aguinaldo','Calcular aguinaldo','SAC completo o proporcional.'],['/trabajo','Más cuentas laborales','Sueldo y derechos.']]),
  '/mx/trabajo/costo-de-un-empleado': b('México · costo patronal', 'IMSS, prima de riesgo y costo anual', 'Sumá cuotas, prestaciones y siniestralidad para comparar puestos y escenarios de contratación.', [['/mx/trabajo/sueldo-neto','Ver sueldo del trabajador','ISR, IMSS y neto.'],['/mx/trabajo/finiquito-y-liquidacion','Calcular salida laboral','Finiquito y liquidación.'],['/mx/trabajo','Más herramientas laborales','Trabajo en México.']]),
  '/calculadora-cientifica': b('Más que una calculadora básica', 'Potencias, raíces, logaritmos y memoria', 'Usá el historial para revisar pasos y pasá a una herramienta específica cuando necesites una explicación.', [['/matematica','Matemática cotidiana','Porcentajes y ecuaciones.'],['/matematica/estadistica-descriptiva','Estadística','Promedios y dispersión.'],['/conversores','Conversores','Unidades y medidas.']]),
  '/hogar/factura-de-luz': b('De kWh a pesos', 'Consumo, tarifa y oportunidades de ahorro', 'Separá potencia y tiempo de uso por aparato y compará el resultado con tu factura real.', [['/calculadora-consumo-electrodomesticos','Consumo por aparato','Potencia, horas y costo.'],['/hogar/subsidios-energia','Revisar subsidios','Segmentación y alcance.'],['/hogar','Más cuentas del hogar','Servicios y mantenimiento.']]),
  '/construccion/ladrillos': b('De la pared a la compra', 'Unidades, juntas y desperdicio', 'Elegí tipo de ladrillo, descontá aberturas y agregá margen según cortes y roturas.', [['/construccion/costo-por-m2','Presupuestar la obra','Costo por etapa y m².'],['/construccion/hormigon','Calcular hormigón','Volumen y materiales.'],['/construccion/pintura','Calcular pintura','Superficie y manos.']]),
  '/construccion/pintura': b('Antes de comprar las latas', 'Superficie, manos, rendimiento y desperdicio', 'Descontá aberturas y ajustá el rendimiento si la pared es nueva, rugosa o cambia mucho de color.', [['/construccion/costo-por-m2','Presupuestar la obra','Costo general por m².'],['/construccion/ladrillos','Calcular mampostería','Paredes y desperdicio.'],['/construccion','Más cuentas de construcción','Materiales y costos.']]),
  '/ec/finanzas-personales/creditos-y-ahorro': b('Ecuador · crédito', 'Cuota, costo total y capacidad de pago', 'Compará préstamo quirografario, BIESS y banco con la misma tasa, plazo y costo total.', [['/ec/finanzas-personales','Más finanzas Ecuador','Crédito y ahorro.'],['/finanzas-personales/prestamo','Comparar sistemas','Cuota, tasa y CFT.'],['/ec/calculadoras','Catálogo Ecuador','Todas las herramientas.']]),
  '/impuestos-argentina': b('Elegí tu situación fiscal', 'Empleado, monotributista, autónomo o titular de bienes', 'Entrá por tu situación para no mezclar obligaciones, topes y vencimientos que funcionan distinto.', [['/impuestos/monotributo','Soy monotributista','Categoría y cuota.'],['/impuestos/ganancias-cuarta-categoria','Trabajo en relación de dependencia','Ganancias y deducciones.'],['/impuestos/bienes-personales','Tengo bienes','Mínimo y escala.']]),
  '/mx/finanzas/credito-de-vivienda': b('México · vivienda', 'Infonavit, banco y capacidad de pago', 'Compará descuento mensual, plazo, costo total y ahorro inicial antes de elegir financiación.', [['/mx/finanzas','Más finanzas México','Crédito, ahorro y vivienda.'],['/mx/trabajo/sueldo-neto','Partir del sueldo neto','ISR, IMSS y bolsillo.'],['/mx/calculadoras','Catálogo México','Todas las herramientas.']]),
  '/tabla/tabla-imc-peso-altura': b('De la tabla a tu caso', 'Ubicá el rango y calculá tu resultado exacto', 'La tabla sirve para orientarte; el IMC exacto y el contexto de salud requieren peso, altura y seguimiento.', [['/salud/peso-ideal-imc','Calcular IMC y rango','Resultado personalizado.'],['/salud/grasa-corporal','Medir composición corporal','Grasa y masa magra.'],['/salud','Más herramientas de salud','Peso, hábitos y nutrición.']]),
  '/co/trabajo/horas-extras-y-recargos': b('Colombia · jornada de 42 horas', 'Hora ordinaria, extra y recargos', 'Partí de la jornada vigente y separá horario diurno, nocturno, dominical y festivo.', [['/co/trabajo/sueldo-neto','Calcular sueldo neto','Aportes y salario.'],['/co/trabajo/costo-de-contratar','Costo para el empleador','Prestaciones y seguridad social.'],['/co/trabajo','Más herramientas laborales','Trabajo en Colombia.']]),
  '/jardin/huerta': b('Calendario por zona', 'Qué sembrar, cuándo y con qué riesgo de helada', 'Elegí ubicación y mes; ajustá por cultivo, método de siembra y condiciones reales de tu lote.', [['/jardin','Más herramientas de jardín','Siembra, poda y riego.'],['/construccion/agua','Calcular agua','Tanques y consumo.'],['/calculadora','Explorar calculadoras','Todo el catálogo.']]),
  '/en': b('Start with the decision', 'What do you need to work out today?', 'Choose a topic and go straight to a focused calculator with clear assumptions and examples.', [['/en/money','Money','Debt, saving and investing.'],['/en/health','Health','Body, nutrition and pregnancy.'],['/en/math','Math','Percentages, statistics and geometry.']]),
  '/viajes/millas': b('Antes de canjear', 'Valor por milla, impuestos y disponibilidad', 'Compará el precio final en efectivo contra las millas más tasas para saber si el canje realmente conviene.', [['/viajes/valen-millas','Calcular valor por milla','Comparar canje y efectivo.'],['/viajes/presupuesto-de-viaje','Armar presupuesto','Transporte, alojamiento y gastos.'],['/viajes','Más herramientas de viaje','Equipaje, horarios y millas.']]),
  '/finanzas-personales': b('Elegí el objetivo', 'Ordenar, ahorrar, salir de deudas o pedir crédito', 'Empezá por una decisión concreta y conectá las cuentas para ver el efecto en tu presupuesto completo.', [['/finanzas-personales/gastos-del-mes','Ordenar gastos','Presupuesto mensual.'],['/finanzas-personales/salir-de-deudas','Salir de deudas','Prioridad y plazo.'],['/finanzas-personales/meta-de-ahorro','Definir una meta','Aporte y tiempo.']]),
  '/datos-topes-sipa-2026': b('Datos previsionales 2026', 'Base mínima, máxima y usos concretos', 'Revisá el período de vigencia y pasá a la calculadora laboral o previsional que usa cada tope.', [['/trabajo/sueldo-bruto-y-neto','Aplicar al sueldo','Aportes y neto.'],['/simulador-jubilacion-anses','Simular jubilación','Edad, aportes y haber.'],['/datasets','Descargar datos','JSON, CSV y fuentes.']]),
  '/buscar': b('Encontrá la cuenta correcta', 'Buscá por problema, no sólo por nombre', 'Probá con “cuánto cobro”, “qué impuesto pago”, “cuánto material necesito” o elegí una categoría.', [['/populares','Ver las más usadas','Herramientas principales.'],['/calculadora','Explorar el catálogo','Todas las calculadoras.'],['/guias','Leer una guía','Explicaciones paso a paso.']]),
};

export function priorityBoostFor(pathname: string): PriorityPageBoost | undefined {
  const path = pathname.replace(/\.html$/, '').replace(/\/$/, '') || '/';
  return PRIORITY_PAGES_31_100[path];
}
