/** Curado tras el crawl completo del 2026-07-28: sólo URLs detectadas con
 * descriptions demasiado cortas. El mapa es explícito para no alterar
 * metadatos sanos ni aplicar texto genérico a páginas futuras. */
export const SEO_DESCRIPTION_OVERRIDES: Record<string, string> = {
  "/alertas": "Sueldo, monotributo, salario mínimo, dólar, impuestos… Encontrá herramientas, ejemplos y fuentes para resolver alertas: te avisamos cuando cambian tus números.",
  "/alquiler": "Calculá ajustes por ICL e IPC, depósito, comisión, expensas y costo total del alquiler con índices y ejemplos actualizados.",
  "/aumento-jubilaciones": "Las jubilaciones aumentan 2,1% en julio 2026 (IPC de mayo… Encontrá herramientas, ejemplos y fuentes para resolver aumento jubilaciones julio 2026: 2,1%.",
  "/auto": "Calculá combustible, costo por kilómetro, patente, seguro, financiación, mantenimiento y costo total de tener un auto.",
  "/auto/consumo": "Medí el consumo real de tu auto en L/100 km y km/L con… Encontrá herramientas, ejemplos y fuentes para resolver cuánto consume mi auto? calculadora de consumo real.",
  "/blog/benchmarks-de-tasa-de-conversion": "CR = (conversiones ÷ visitas) × 100. Ejemplo: 250 ventas… Incluye explicación, ejemplo resuelto y pasos para aplicar benchmarks de tasa de conversión.",
  "/blog/el-aire-acondicionado-necesario-con-ejemplos-paso-a-paso": "Regla base: 100 frig/m² en ambiente de orientación… Incluye explicación, ejemplo resuelto y pasos para aplicar el aire acondicionado necesario con ejemplos paso a paso.",
  "/blog/el-capital-de-trabajo-con-ejemplos-paso-a-paso": "El capital de trabajo neto es activos corrientes menos… Incluye explicación, ejemplo resuelto y pasos para aplicar el capital de trabajo con ejemplos paso a paso.",
  "/blog/el-poder-de-compra-con-ejemplos-paso-a-paso": "Con 30% de inflación anual, $100.000 de hoy valen… Incluye explicación, ejemplo resuelto y pasos para aplicar el poder de compra con ejemplos paso a paso.",
  "/blog/el-precio-por-kilo-con-ejemplos-paso-a-paso": "Comparador precio por kg/L: cuál conviene según… Incluye explicación, ejemplo resuelto y pasos para aplicar el precio por kilo con ejemplos paso a paso.",
  "/blog/el-sac-proporcional-con-ejemplos-paso-a-paso": "Se parte del 50% de la mejor remuneración mensual del… Incluye explicación, ejemplo resuelto y pasos para aplicar el sac proporcional con ejemplos paso a paso.",
  "/blog/ingresos-brutos-con-ejemplos-paso-a-paso": "IIBB = facturación del período neta de IVA × alícuota… Incluye explicación, ejemplo resuelto y pasos para aplicar ingresos brutos con ejemplos paso a paso.",
  "/blog/la-capacidad-de-endeudamiento-con-ejemplos-paso-a-paso": "El ratio deuda/ingreso divide todos los pagos… Incluye explicación, ejemplo resuelto y pasos para aplicar la capacidad de endeudamiento con ejemplos paso a paso.",
  "/blog/la-nota-necesaria-para-aprobar-con-ejemplos-paso-a-paso": "¿Tenés parciales rendidos y necesitás saber qué nota… Incluye explicación, ejemplo resuelto y pasos para aplicar la nota necesaria para aprobar con ejemplos paso a paso.",
  "/blog/las-percepciones-impositivas-con-ejemplos-paso-a-paso": "Calculá una percepción a partir de la base y la… Incluye explicación, ejemplo resuelto y pasos para aplicar las percepciones impositivas con ejemplos paso a paso.",
  "/blog/los-costos-fijos-y-variables-con-ejemplos-paso-a-paso": "El costo total suma costos fijos y costo variable por… Incluye explicación, ejemplo resuelto y pasos para aplicar los costos fijos y variables con ejemplos paso a paso.",
  "/blog/ltv-vs-cac": "CAC es cuánto cuesta cada cliente nuevo sumando todas las inversiones marketing+ventas. Incluye explicación, ejemplo resuelto y pasos para aplicar ltv vs cac.",
  "/blog/numeros-emprendimiento": "Guía práctica con calculadoras conectadas para los… Incluye explicación, ejemplo resuelto y pasos para aplicar los cinco números que ordenan un emprendimiento.",
  "/blog/que-es-la-comparacion-de-precios": "Dividí el precio de cada opción por su cantidad en la misma… Incluye explicación, ejemplo resuelto y pasos para aplicar qué es la comparación de precios.",
  "/cambio-de-monedas": "Cotizaciones en vivo de dólar blue, oficial, MEP, CCL, tarjeta, cripto, euro… Encontrá herramientas, ejemplos y fuentes para resolver cambio de monedas hoy.",
  "/cl/impuestos/cobre-y-finanzas-publicas": "Hub de decisión con 1 cálculos: Calculadora de impacto… Consultá cómo impacta el precio del cobre en los ingresos fiscales con datos, herramientas y fuentes para Chile.",
  "/cl/trabajo/me-quedo-sin-trabajo": "Calcula tu finiquito completo en Chile: indemnización… Consultá finiquito en chile: cuánta plata te corresponde con datos, herramientas y fuentes para Chile.",
  "/co/automotor/costo-de-tener-carro": "Sumá el costo real anual de tu vehículo en Colombia… Consultá cuánto cuesta tener carro o moto en colombia con datos, herramientas y fuentes para Colombia.",
  "/co/impuestos/retencion-en-la-fuente": "Calculá la retención en la fuente en Colombia: salario… Consultá retención en la fuente colombia: cuánto te retienen o cuánto con datos, herramientas y fuentes para Colombia.",
  "/cocina": "Convertí tazas y gramos, ajustá recetas y calculá porciones, ingredientes, tiempos y cantidades para cocinar sin desperdiciar.",
  "/construccion": "Calculá materiales, metros cuadrados, hormigón, ladrillos, pintura, pisos, techos y costos de obra antes de comprar o construir.",
  "/construccion/ladrillos": "Calculá cuántos ladrillos, bloques o adoquines… Encontrá herramientas, ejemplos y fuentes para resolver cuántos ladrillos necesito? calculadora por m² de pared.",
  "/construccion/pintura": "Calculá cuántos litros de pintura necesitás y, sobre… Encontrá herramientas, ejemplos y fuentes para resolver cuántos litros de pintura necesito? calculadora de latas.",
  "/conversores": "Convertí longitud, peso, volumen, temperatura, tiempo, monedas, medidas de cocina, talles y formatos con equivalencias explicadas.",
  "/conversores/numeros-a-letras": "Escribí un número en letras para un cheque o un pagaré… Encontrá herramientas, ejemplos y fuentes para resolver pasar números a letras, romanos y binario.",
  "/cuando-juega-ecuador-mundial-2026": "La página que buscás no existe. Explorá nuestras calculadoras online… Encontrá herramientas, ejemplos y fuentes para resolver página no encontrada (404).",
  "/datos-topes-sipa-2026": "Base imponible máxima de aportes personales en… Encontrá herramientas, ejemplos y fuentes para resolver topes sipa 2026: base imponible máxima de aportes.",
  "/embarazo/dias-fertiles": "Calculá tu ventana fértil y el día de ovulación según tu ciclo, tengas… Encontrá herramientas, ejemplos y fuentes para resolver cuáles son mis días fértiles.",
  "/embeber": "Calculadoras listas para embeber en tu sitio web: widgets gratis, sin registro y con ejemplos para WordPress, Blogger, Wix, Squarespace o cualquier HTML.",
  "/en/cooking/how-much-food-per-guest": "Work out exactly how much meat, pizza, empanadas… Encontrá herramientas, ejemplos y fuentes para resolver how much food per person? party portion calculator.",
  "/es/automotor": "Comprar y mantener un coche en España: impuestos, ITV, seguro, etiqueta DGT y coste… Consultá coche en españa con datos, herramientas y fuentes para España.",
  "/es/educacion": "Cuánto cuesta estudiar en España y qué nota necesitas: grados, FP, másteres… Consultá educación en españa con datos, herramientas y fuentes para España.",
  "/estudio": "Calculá notas, promedios, asistencia, tiempos de lectura y planes de estudio con procedimientos claros y ejemplos resueltos.",
  "/eventos/logistica": "Calculá mesas, sillas, mozos, vajilla, cotillón… Encontrá herramientas, ejemplos y fuentes para resolver cuántas mesas, sillas y meseros necesito para la fiesta.",
  "/fechas": "Calculá días entre fechas, días hábiles, edades, aniversarios, vencimientos y cuánto falta para una fecha con calendarios actualizados.",
  "/fechas/edad-exacta": "Tu edad exacta al día: años, meses y días cumplidos… Encontrá herramientas, ejemplos y fuentes para resolver qué edad tengo exactamente? años, meses, días, semanas.",
  "/finanzas-personales": "Cuota de préstamo, plazo fijo, interés compuesto, CFT, crédito UVA… Encontrá herramientas, ejemplos y fuentes para resolver finanzas personales y créditos.",
  "/goleadores-mundial-2026": "Tabla final de goleadores del Mundial 2026: Kylian Mbappé (Francia)… Encontrá herramientas, ejemplos y fuentes para resolver goleadores del mundial 2026.",
  "/hogar/amueblar": "Qué TV, mesa, colchón, placard, escritorio, cortina o… Encontrá herramientas, ejemplos y fuentes para resolver qué medida de mueble entra en mi ambiente.",
  "/hogar/gastos-de-la-casa": "Expensas, mantenimiento anual, seguro de hogar, cuándo… Encontrá herramientas, ejemplos y fuentes para resolver cuánto me cuesta la casa además del alquiler o la cuota.",
  "/impuestos": "Calculá IVA, Ganancias, Monotributo, Ingresos Brutos, retenciones y otros impuestos con parámetros vigentes y fuentes oficiales.",
  "/impuestos-argentina": "Monotributo 2026 por categoría, Ganancias sobre el sueldo, IVA, Bienes… Encontrá herramientas, ejemplos y fuentes para resolver impuestos en argentina 2026.",
  "/inflacion-argentina": "Inflación en Argentina hoy: dato mensual del INDEC… Encontrá herramientas, ejemplos y fuentes para resolver inflación argentina hoy: mensual, interanual y uva.",
  "/jardin": "Calculá tierra, macetas, riego, cantidad de plantas, semillas y calendario de huerta según espacio, clima y necesidades del cultivo.",
  "/jubilacion": "Estimá jubilación, años de aportes, moratorias, pensiones y haberes ANSES con requisitos, fuentes oficiales y valores vigentes.",
  "/mascotas": "Calculá edad, alimento, peso, gestación, costos y cuidados de perros, gatos y otras mascotas con referencias veterinarias y límites claros.",
  "/matematica": "Resolvé porcentajes, ecuaciones, matrices, geometría, estadística, límites e integrales con fórmulas, ejemplos y procedimiento explicado.",
  "/matematica/regla-de-tres": "Regla de tres simple directa e inversa, compuesta, escala de plano o… Encontrá herramientas, ejemplos y fuentes para resolver cómo hago una regla de tres.",
  "/mx": "Calculadoras de México actualizadas a 2026 para sueldo neto, ISR, IMSS, aguinaldo, finiquito, vivienda y trámites, con fuentes oficiales.",
  "/mx/tramites": "Pasaporte, INE, RFC y licencia de conducir: cuánto cuesta cada documento y qué… Consultá trámites en méxico con datos, herramientas y fuentes para México.",
  "/nutricion/calorias-diarias": "Calculá tus calorías diarias con Mifflin-St Jeor… Encontrá herramientas, ejemplos y fuentes para resolver cuántas calorías necesito por día? calculadora de tdee.",
  "/ocio": "Planificá actividades, juegos, salidas, lecturas y tiempo libre con calculadoras prácticas de costos, duración y organización.",
  "/pe/auto": "SOAT, revisión técnica, impuesto vehicular y combustible: cuánto cuesta tener el auto al… Consultá auto en perú con datos, herramientas y fuentes para Perú.",
  "/pe/estudio": "¿Cuánto cuesta estudiar y qué nota necesito?. Consultá estudiar en perú con datos, herramientas y fuentes para Perú.",
  "/pe/estudio/estudiar-y-aprobar": "Hub de decisión con 2 cálculos: ¿Cuánto cuesta estudiar en… Consultá cuánto cuesta estudiar y qué nota necesito con datos, herramientas y fuentes para Perú.",
  "/pe/hogar/costo-de-construir": "Hub de decisión con 1 cálculos: Calculadora de Costo de Construcción… Consultá cuánto cuesta construir mi casa con datos, herramientas y fuentes para Perú.",
  "/precio-nafta-hoy": "Precio promedio de la nafta y el gasoil hoy en Argentina: súper… Encontrá herramientas, ejemplos y fuentes para resolver precio de la nafta hoy en argentina.",
  "/pt/casa": "Quanto de energia minha casa consome?. Consultá energia da casa con datos, herramientas y fuentes para Brasil.",
  "/pt/quando-joga-brasil-copa-2026": "Veja o calendário do Brasil na Copa do Mundo 2026, com datas, horários, resultados e o caminho completo que a seleção percorreu no torneio.",
  "/pt/trabalho/beneficios-do-governo": "Calcule o valor do Bolsa Família pela regra da Lei… Consultá bolsa família e abono pis/pasep: tenho direito e de quanto con datos, herramientas y fuentes para Brasil.",
  "/pt/vida": "Qual é o número para decidir melhor no dia a dia?. Consultá cálculos do dia a dia con datos, herramientas y fuentes para Brasil.",
  "/salud/ritmo-y-pace": "Calculá tu pace en min/km, la velocidad en km/h y cuánto te daría otra… Encontrá herramientas, ejemplos y fuentes para resolver a qué ritmo tengo que correr.",
  "/tecnologia": "Calculá consumo, baterías, almacenamiento, bitrate, redes, componentes electrónicos y ajustes de dispositivos con herramientas gratuitas.",
  "/trabajo": "Lo que cobrás, lo que te descuentan y lo que te corresponde cuando el trabajo empieza… Encontrá herramientas, ejemplos y fuentes para resolver trabajo.",
  "/trabajo/liquidacion-final": "Si renunciás no cobrás indemnización por antigüedad… Encontrá herramientas, ejemplos y fuentes para resolver renuncio: ¿cuánto cobro de liquidación final.",
  "/trabajo/sueldos-por-convenio": "Elegí tu gremio y mirá el básico de convenio vigente, la antigüedad… Encontrá herramientas, ejemplos y fuentes para resolver cuánto gana un… según convenio.",
  "/ve/trabajo/liquidacion-lottt": "Calculá tu liquidación completa en Venezuela con la… Consultá liquidación en venezuela (lottt): prestaciones, vacaciones con datos, herramientas y fuentes para Venezuela.",
  "/ve/vida": "¿Qué número necesito para mi salud, estudio o trámite?. Consultá salud, estudio y trámites con datos, herramientas y fuentes para Venezuela.",
  "/vencimientos-afip-2026": "Calendario completo de vencimientos AFIP 2026… Encontrá herramientas, ejemplos y fuentes para resolver vencimientos afip 2026: calendario fiscal completo mes.",
  "/viajes": "Planificá combustible, peajes, distancias, tiempos, equipaje, cambio de moneda y división de gastos antes de viajar.",
  "/vivienda": "Calculá alquiler, ajustes, crédito hipotecario, gastos de compra, impuestos y costos mensuales para decidir sobre tu vivienda.",
};

export function seoDescriptionFor(path: string, fallback: string): string {
  return SEO_DESCRIPTION_OVERRIDES[path] ?? fallback;
}
