import type { HubData } from './types';
export const hub: HubData = {
  slug: 'tecnologia/comparar-textos-y-listas',
  title: 'Comparar textos y listas: diferencias y duplicados | Hacé Cuentas',
  description: 'Compará dos textos por líneas, encontrá elementos exclusivos o comunes entre listas y quitá duplicados. Procesamiento local, conteos claros, copiar y descargar TXT.',
  silo: 'Tecnología',
  siloHref: '/tecnologia',
  eyebrow: 'Dos versiones, una comparación',
  h1: '¿Qué cambió entre estos textos o listas?',
  lede: 'Pegá dos versiones para revisar líneas agregadas y eliminadas. Si tenés listas, encontrá faltantes, elementos comunes o una unión sin duplicados. Todo el procesamiento de esta herramienta se hace en tu navegador.',
  stamps: ['Comparación local', 'Texto literal', 'Revisado 04-10-2026'],
  resultLabel: 'Diferencias y elementos',
  inputsTitle: 'Elegí qué querés comparar',
  inputsIntro: 'Cada entrada admite hasta 30.000 caracteres. El modo texto admite 250 líneas por versión; las listas, 2.000 elementos antes de descartar vacíos. Las opciones de espacios y mayúsculas son explícitas y están desactivadas al empezar.',
  fields: [],
  fineprint: 'No guarda tus textos ni los incorpora a URLs o eventos de Analytics.',
  chart: { type: 'steps', caption: 'Los resultados distinguen líneas agregadas/eliminadas y elementos únicos de apariciones repetidas.' },
  breakdownTitle: 'Resultado de la comparación', breakdownIntro: 'Las etiquetas explican cada diferencia sin depender del color.',
  answer: { title: 'Texto y listas responden preguntas distintas.', copy: 'El texto se compara por líneas respetando el orden. Las listas se comparan como conjuntos de elementos únicos: las repeticiones se cuentan aparte. Esta es una comparación literal, no semántica.', yes: ['Líneas agregadas, eliminadas y conservadas.', 'Solo A, solo B, comunes y unión de listas.', 'Eliminar duplicados preservando la primera aparición.'], warn: ['No detecta plagio ni mide similitud de significado.', 'Una línea movida aparece como eliminación y agregado.', 'Coma y punto y coma son separadores literales: no interpreta CSV con comillas.'], plazo: 'Elegí primero si el orden del texto importa o si buscás elementos en una lista.' },
  faq: [
    { q: '¿Mis textos se suben a un servidor?', a: 'La comparación se ejecuta en memoria dentro de tu navegador. Esta herramienta no envía el contenido, no lo incorpora a eventos de Analytics, no lo agrega a la URL ni lo guarda en almacenamiento persistente. Los controles y resultados están enmascarados para las grabaciones de sesiones del sitio. Copiar y descargar solo se activan cuando lo pedís. Al editar el contenido, las reglas o el separador, el resultado y la copia anterior se retiran hasta volver a comparar.' },
    { q: '¿Qué se considera un cambio en el modo texto?', a: 'Una línea eliminada deja de aparecer en la versión B y una agregada aparece solo allí. Se conserva la secuencia común más larga para alinear ambas versiones. No se buscan diferencias dentro de cada palabra. Un cambio de orden puede aparecer como eliminar una línea y agregarla en otra posición.' },
    { q: '¿Una lista con tres repeticiones cuenta como tres elementos comunes?', a: 'No. El resultado de conjuntos cuenta cada elemento una vez. Para A = pera, pera, uva y B = uva, kiwi, uva, los comunes son solo uva y la unión es pera, uva, kiwi. A y B tienen tres apariciones, dos únicos y una repetición cada una.' },
    { q: '¿Ignora mayúsculas, espacios o tildes?', a: 'Por defecto distingue mayúsculas y espacios. Podés ignorar mayúsculas o quitar espacios al principio y al final; no se colapsan espacios internos. Las tildes y la ñ siguen siendo significativas: año y ano son distintos. Se normaliza Unicode NFC, por lo que dos representaciones equivalentes de é coinciden.' },
    { q: '¿Cómo se elige el separador de una lista?', a: 'Elegí un elemento por línea, separado por comas o separado por punto y coma. El separador es literal: no se interpretan comillas ni escapes CSV. Los fragmentos vacíos se descartan; un fragmento con espacios solo se descarta si activás quitar espacios en los extremos. La salida usa un elemento por línea.' },
    { q: '¿En qué orden queda una lista sin duplicados?', a: 'Se mantiene la primera aparición de cada elemento en A. Los exclusivos de B conservan el orden de B. Los comunes usan la primera representación de A; la unión empieza con A y agrega los exclusivos de B. Si quitás espacios en los extremos, esa limpieza también se refleja en la salida.' },
    { q: '¿Los saltos de línea de Windows y Mac cambian el resultado?', a: 'Los finales CRLF y CR se convierten a LF antes de comparar. En el modo texto, las líneas vacías y un salto al final sí son parte del contenido. En listas, los elementos vacíos se descartan según las reglas del separador y la limpieza elegida.' },
    { q: '¿Puedo comparar HTML o detectar plagio?', a: 'Podés pegar HTML para comparar su texto literal: no se ejecutan etiquetas, imágenes ni scripts. La herramienta no verifica autoría, plagio ni equivalencia semántica. Para esas preguntas hacen falta otros criterios y evidencia.' },
  ],
  sources: [
    { name: 'Conjuntos de valores únicos y orden de inserción', publisher: 'MDN Web Docs', url: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set' },
    { name: 'Normalización Unicode de cadenas', publisher: 'MDN Web Docs', url: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/normalize' },
  ],
  replaces: [],
  lastReviewed: '2026-10-04',
  audience: 'global',
};
