import type { HubData } from './types';
const LEGAL = 'Estimación informativa. Revisá la fecha, el contrato, la jurisdicción y el régimen aplicable. Ante una controversia, consultá a un profesional; este cálculo no garantiza un derecho ni una devolución.';
export const hub: HubData = {
 slug: 'alquiler/entrar-a-un-alquiler',
 title: '¿Cuánta plata necesito para alquilar? Entrada, depósito y comparación de propiedades',
 description: 'Sumá primer mes, expensas, depósito pactado, comisión y caución cotizadas. Compará dos propiedades por entrada y costo mensual y revisá tu presupuesto.',
 silo: 'Alquiler', siloHref: '/alquiler', eyebrow: 'Antes de reservar',
 h1: '¿Cuánta plata necesito para entrar a un alquiler?',
 lede: 'Calculá los importes pactados y cotizados. Separá dinero inmovilizado de gastos definitivos y compará dos propiedades con el mismo presupuesto.',
 stamps: ['Revisado 30-09-2026', 'Depósito: art. 1196 vigente', 'Ejemplos editables'],
 resultLabel: 'Plata de entrada estimada',
 cases: {title:'¿Cuál es tu situación?',intro:'Los importes son editables; cada modo responde una decisión diferente.',items:[
  {id:'deposito',label:'Entrada con depósito',hint:'Importes pactados',answer:'Entrada = primer mes + expensas + depósito + comisión cotizada + otros.',yes:['Sumá los gastos iniciales reales','Separá el depósito inmovilizado del gasto definitivo'],warn:[LEGAL],plazo:'Confirmá condiciones antes de reservar.'},
  {id:'caucion',label:'Entrada con caución',hint:'Cotización real',answer:'La prima cotizada se suma al depósito si también lo exige el contrato.',yes:['Cargá prima total con impuestos','Mantené el depósito pactado si corresponde'],warn:[LEGAL,'La caución no elimina automáticamente el depósito.'],plazo:'Pedí cotización y cobertura por escrito antes de reservar.'},
  {id:'presupuesto',label:'Presupuesto según ingreso',hint:'Criterio editable',answer:'Alquiler máximo = presupuesto de vivienda menos expensas y servicios.',yes:['Elegí el porcentaje del ingreso','Considerá ajustes futuros y otros gastos'],warn:[LEGAL,'El porcentaje es una preferencia presupuestaria, no una regla legal.'],plazo:'Revisá el presupuesto en cada ajuste.'},
  {id:'devolucion',label:'Devolución del depósito',hint:'Contrato y régimen',answer:'Devolución estimada = monto pactado menos descuentos documentados.',yes:['Revisá monto, moneda y condiciones','Conservá recibos y acta de entrega'],warn:[LEGAL,'No se presume actualización al último alquiler.'],plazo:'Usá el plazo pactado y verificá el régimen aplicable.'},
  {id:'quien-paga',label:'Responsabilidades',hint:'Detalle de gastos',answer:'Revisá gastos habituales, servicios y cargas del inmueble según contrato y art. 1209.',yes:['Pedí la liquidación detallada','Cargá sólo los gastos mensuales a tu cargo'],warn:[LEGAL],plazo:'Revisá cada liquidación antes de pagar.'},
 ]},
 inputsTitle: 'Tu contrato y tu presupuesto', inputsIntro: 'Todos los importes deben estar en la misma moneda. Reemplazá los ejemplos por condiciones reales.',
 fields: [
  {id:'alquiler',label:'Alquiler mensual',prefix:'$',value:'650.000',thousands:true},
  {id:'expensas',label:'Expensas mensuales cotizadas',prefix:'$',value:'121.000',thousands:true},
  {id:'deposito',label:'Depósito pactado',prefix:'$',value:'650.000',thousands:true},
  {id:'caucion',label:'Cotización total de caución, si corresponde',prefix:'$',value:'0',thousands:true},
  {id:'comision',label:'Comisión cotizada a tu cargo',prefix:'$',value:'0',thousands:true},
  {id:'ingreso',label:'Ingreso neto mensual',prefix:'$',value:'2.200.000',thousands:true},
 ],
 fineprint: LEGAL,
 chart: {type:'bars',title:'Dos propiedades',caption:'Compará por separado el desembolso inicial y el costo mensual; no son el mismo criterio.'},
 breakdownTitle:'Cada rubro de la entrada',breakdownIntro:'La caución es una prima no recuperable; el depósito se devuelve según las condiciones y el régimen del contrato.',
 faq: [
  {q:'¿Cuánta plata necesito para entrar a un alquiler?',a:'Sumá primer mes, expensas iniciales, depósito pactado, comisión a tu cargo, caución cotizada y otros gastos. En el ejemplo de vivienda en CABA: $650.000 + $121.000 + $650.000 de depósito = $1.421.000, equivalentes a 2,19 alquileres. No incluye comisión al inquilino persona física ni mudanza. Cambiar cualquier importe cambia el total.'},
  {q:'¿Cuánto es el depósito de garantía hoy?',a:'El art. 1196 vigente del Código Civil y Comercial permite pactar monto, moneda y forma de devolución del depósito. Un mes es sólo el ejemplo editable de esta página, no un límite legal. Los contratos anteriores pueden tener otro régimen: revisá la fecha y el texto aplicable.'},
  {q:'¿Cómo se calcula la devolución del depósito?',a:'Cargá el monto que resulte de las condiciones de devolución de tu contrato y los descuentos documentados. El régimen actual no obliga automáticamente a actualizarlo al último alquiler. Para contratos habitacionales sujetos a la ley 27.551, el texto de ese régimen limitaba el depósito a un mes del alquiler inicial y preveía devolución equivalente al último mes. Confirmá cuál corresponde antes de calcular.'},
  {q:'¿Cuánto sale un seguro de caución?',a:'Usá una cotización real con el costo total, impuestos, cobertura, plazo y forma de pago. Esta página no presume una prima de mercado. Si todavía no la tenés, el modo caución muestra que falta cotización; no interpreta esa ausencia como costo cero.'},
  {q:'¿La caución reemplaza al depósito?',a:'No automáticamente. La póliza puede sustituir la garantía propietaria aceptada por el locador, y el contrato puede exigir además un depósito. Cargá ambos importes si corresponde. La prima de caución no se recupera y no libera al inquilino de sus obligaciones.'},
  {q:'¿Quién paga la comisión inmobiliaria?',a:'La ley 5.859 de CABA prohíbe cobrar comisión y gastos de gestoría al inquilino persona física en alquiler de vivienda. Para PBA, cargá la comisión de tu cotización y revisá la normativa local; no se presupone una división por mitades ni una tasa fija. Si el contrato no es de vivienda o el inquilino es una persona jurídica, verificá las reglas aplicables.'},
  {q:'¿Qué entra en el costo mensual?',a:'Alquiler, expensas de gastos habituales y servicios que hayas cargado. El desembolso inicial incluye una sola vez el primer mes y las expensas de entrada. El depósito se informa como dinero inmovilizado. No se calculan ajustes futuros, reparaciones ni costos omitidos.'},
  {q:'¿Las expensas se estiman por metro cuadrado?',a:'No. Cargá la liquidación o una estimación propia identificada como tal. Edificio, servicios, superficie y fecha cambian el costo; un precio fijo por metro cuadrado sin una fuente vigente puede desorientarte.'},
  {q:'¿El 30% del ingreso es un requisito legal?',a:'No: es un criterio de presupuesto editable. La cuenta divide el costo mensual por el porcentaje que elegís. No determina si una inmobiliaria aceptará tus ingresos, ni garantiza que te alcance: considerá otras deudas, gastos y futuros ajustes.'},
  {q:'¿Cómo comparo dos propiedades?',a:'A toma los datos del formulario principal; B permite cargar sus propios alquiler, expensas, depósito, comisión, caución, otros costos y servicios. Mirá la diferencia inicial y mensual por separado. Una propiedad puede exigir menos para entrar y costar más cada mes.'},
  {q:'¿Quién paga impuestos y expensas?',a:'El art. 1209 distingue gastos habituales vinculados a servicios del inmueble de cargas que gravan la cosa y expensas extraordinarias. La etiqueta ordinaria o extraordinaria no basta: pedí la liquidación detallada y revisá contrato, régimen y normativa aplicable. La herramienta sólo suma los gastos que cargás.'},
  {q:'¿Puedo negociar las condiciones de entrada?',a:'Pedí por escrito los importes, cobertura de garantías y condiciones de devolución antes de reservar. Las condiciones negociables dependen de las partes y de las normas aplicables; esta estimación no valida cláusulas ni resuelve controversias.'},
 ],
 sources: [
  {name:'Código Civil y Comercial actualizado — arts. 1196 y 1209',url:'https://www.argentina.gob.ar/normativa/nacional/ley-26994-235975/actualizacion',publisher:'Argentina.gob.ar',date:'Consultado 2026-09-30'},
  {name:'Ley 5.859 CABA — comisión en locaciones de vivienda',url:'https://boletinoficial.buenosaires.gob.ar/normativaba/norma/398889',publisher:'Boletín Oficial CABA'},
  {name:'Ley 27.551 — texto del régimen anterior',url:'https://www.boletinoficial.gob.ar/detalleAviso/primera/231663/20200630',publisher:'Boletín Oficial',date:'2020-06-30'},
  {name:'SSN — aseguradoras autorizadas y normativa',url:'https://www.argentina.gob.ar/ssn',publisher:'Superintendencia de Seguros de la Nación'},
 ],
  replaces: [
    '/calculadora-cuanto-alquiler-puedo-pagar-sueldo-argentina',
    '/calculadora-sueldo-minimo-para-alquilar',
    '/calculadora-depositos-alquiler-cuantos-meses-devolucion',
    '/calculadora-comision-inmobiliaria-alquiler-caba-pba',
    '/calculadora-seguro-caucion-alquiler-costo-mensual',
    '/calculadora-abl-expensas-quien-paga-inquilino-propietario',
    '/calculadora-expensas-departamento-calcular-m2-categoria',
    '/calculadora-desalojo-causa-plazos-honorarios-juicio',
    // Absorbidas en el cierre del catálogo (27-07-2026): ya no existen como calc suelta.
    '/calculadora-poliza-juridica-arrendamiento-mexico',
  ],
 lastReviewed:'2026-09-30', audience:'AR',
};
