import type { HubData } from './types';
export const hub: HubData = {
  slug: 'matematica/operaciones-paso-a-paso',
  title: 'División larga y multiplicación paso a paso, con decimales | Hacé Cuentas',
  description: 'Resolvé divisiones largas y multiplicaciones en columnas. Mostrá cada cifra, acarreo, resto y comprobación con enteros o decimales; copiá o imprimí el procedimiento.',
  silo: 'Matemática',
  siloHref: '/matematica',
  eyebrow: 'Aritmética que podés comprobar',
  h1: '¿Cómo divido o multiplico paso a paso?',
  lede: 'Elegí división larga o multiplicación en columnas y mirá cómo se obtiene cada cifra. Esta herramienta explica dos números no negativos: no resuelve expresiones completas ni reemplaza la calculadora de fracciones.',
  stamps: ['Enteros y decimales', 'Sin registro', 'Revisado 04-10-2026'],
  resultLabel: 'Resultado y procedimiento',
  inputsTitle: 'Los dos números de tu cuenta',
  inputsIntro: 'Acepta coma o punto decimal, sin separadores de miles. Hasta 12 cifras por número, 6 decimales por entrada y 12 decimales en el cociente. La multiplicación es exacta; la división se trunca a la precisión elegida y conserva el resto.',
  fields: [{ id: 'first', label: 'Primer número', value: '1005' }, { id: 'second', label: 'Segundo número', value: '5' }],
  fineprint: 'El resto decimal se expresa en las unidades originales del dividendo.',
  chart: { type: 'steps', caption: 'Cada fila muestra una cifra del cociente o un producto parcial; los ceros mantienen su posición.' },
  breakdownTitle: 'El procedimiento', breakdownIntro: 'Revisá cada paso y la comprobación exacta.',
  answer: { title: 'Dividir es hallar un cociente y conservar el resto; multiplicar es sumar productos parciales.', copy: 'El resultado viene acompañado del procedimiento, para que puedas localizar una cifra incorrecta y comprobar tu trabajo.', yes: ['División larga con ceros intermedios y resto.', 'Multiplicación por cifra, desplazamiento y acarreo.', 'Comprobación exacta de los números ingresados.'], warn: ['No admite números negativos, fracciones escritas con barra ni expresiones.', 'Un cociente truncado no es el valor exacto si queda resto.'], plazo: 'Compará primero el resultado, después las filas del procedimiento.' },
  faq: [
    { q: '¿Por qué aparece un cero en el medio del cociente?', a: 'Si el número parcial es menor que el divisor, esa posición aporta cero. En 1005 ÷ 5, el cociente es 201: el cero de las decenas no se puede omitir. El tablero conserva también ceros iniciales de alineación, que no cambian el valor.' },
    { q: '¿Cómo se divide cuando el divisor tiene decimales?', a: 'La cuenta muestra una transformación equivalente con ambos números enteros. Por ejemplo, 12,5 ÷ 0,25 se trabaja como 1250 ÷ 25 y da 50. La comprobación vuelve a los números originales.' },
    { q: '¿El resultado de 7 ÷ 12 es exacto?', a: 'Con seis decimales aparece 0,583333, truncado. Queda un resto de 0,000004 en las unidades del 7 original. Por eso la comprobación es 0,583333 × 12 + 0,000004 = 7. Más decimales reducen el resto, sin convertir un decimal periódico en finito.' },
    { q: '¿Qué significa el resto entero y el resto después de los decimales?', a: 'El resto entero es lo que queda antes de continuar con cifras decimales. El segundo es lo que falta tras la precisión elegida. Ambos se muestran en las unidades originales y pueden ser distintos; con precisión cero coinciden.' },
    { q: '¿Cómo veo los acarreos de una multiplicación?', a: 'Debajo de cada producto parcial se detalla la cifra multiplicada, el acarreo recibido, la cifra que se escribe y el acarreo que pasa a la izquierda. Los parciales se alinean por posición antes de sumarlos.' },
    { q: '¿Acepta coma y punto decimal?', a: 'Sí. 1,2 y 1.2 representan el mismo número. No uses separadores de miles: para mil cinco escribí 1005. No admite notación científica ni signos negativos. Los resultados usan coma decimal.' },
    { q: '¿Por qué 1,2 × 0,03 da 0,036?', a: 'El tablero trabaja con 12 × 3 = 36 y devuelve tres posiciones decimales: una del primer número y dos del segundo. El cálculo usa enteros exactos, de modo que el resultado no muestra un residuo de coma flotante.' },
    { q: '¿Puedo copiar o imprimir el procedimiento?', a: 'Sí. Copiar incluye resultado, tablero, pasos y comprobación. Imprimir abre la opción de impresión del navegador. Al cambiar los números o la precisión, volvé a mostrar el procedimiento: la copia y la impresión se habilitan con el resultado actualizado. Si el portapapeles no está disponible, la herramienta ofrece el texto seleccionable para copiar a mano.' },
  ],
  sources: [
    { name: 'División de números enteros', publisher: 'OpenStax · Prealgebra 2e', url: 'https://openstax.org/books/prealgebra-2e/pages/1-5-divide-whole-numbers' },
    { name: 'Operaciones con decimales', publisher: 'OpenStax · Prealgebra 2e', url: 'https://openstax.org/books/prealgebra-2e/pages/5-2-decimal-operations' },
  ],
  replaces: [],
  lastReviewed: '2026-10-04',
  audience: 'global',
};
