import type { HubData } from '../types';

export const hub: HubData = {
  slug: 'en/cars/buy-lease-finance',
  title: 'Should I buy, lease or finance a car? Total ownership calculator',
  description: 'Compare cash ownership, financing and leasing after taxes, dealer fees, interest, maintenance, lease payments and estimated resale value.',
  silo: 'Cars',
  siloHref: '/en/cars',
  locale: 'en',
  eyebrow: 'United States · car-buying decisions',
  h1: 'Should I buy, lease or finance this car?',
  lede: 'A monthly payment can make a car look cheap while the total cost keeps growing. Compare cash, financing and leasing on the same price, horizon, maintenance and resale assumptions.',
  stamps: ['USD total-cost comparison', 'Monthly payment and ownership cost', '7 calculators inside'],
  resultLabel: 'Estimated cost of your route',
  cases: {
    title: 'Which route are you considering?',
    intro: 'Pick the route you are most likely to use. The calculator keeps all three alternatives visible so you can compare the number that matters over the same horizon.',
    items: [
      { id: 'finance', label: 'I will finance the purchase', hint: 'Payment and interest', answer: 'Financing turns the vehicle price into a monthly payment, but interest and the down payment determine the total cash committed.', yes: ['Amount financed after down payment and trade equity', 'Monthly payment and total interest', 'Maintenance over the ownership horizon', 'Estimated total cost after resale'], warn: ['Compare APR, term, fees and total of payments — not just the advertised monthly payment.', 'A longer term can lower the payment while increasing interest and leaving you owing more than the car is worth.'], plazo: 'the lender provides the full APR and amount financed in writing.' },
      { id: 'lease', label: 'I will lease it', hint: 'Payments and buyout', answer: 'A lease trades ownership for a defined term of payments, a due-at-signing amount and possible buyout, mileage and wear charges.', yes: ['Due-at-signing amount and monthly lease payment', 'Lease length', 'End-of-term buyout', 'Maintenance and the total scheduled cash cost'], warn: ['Add taxes, acquisition fees, disposition fees, excess mileage and wear charges if they are not in the quote.', 'A lease payment is not an ownership cost unless you compare the same time horizon and end-of-term choice.'], plazo: 'you read the lease worksheet and mileage, wear and buyout clauses.' },
      { id: 'cash', label: 'I will pay cash', hint: 'Net ownership cost', answer: 'Cash avoids loan interest, but the economic cost still includes taxes, fees, maintenance and the vehicle value you can recover when you sell it.', yes: ['Cash purchase cost', 'Taxes and dealer fees', 'Maintenance over the horizon', 'Estimated value recovered at resale'], warn: ['Paying cash can reduce liquidity. Keep the emergency reserve and opportunity cost in the broader decision.', 'Resale value is an assumption, not a guarantee; test a lower percentage for a conservative view.'], plazo: 'the cash price, included fees and expected delivery are confirmed.' },
    ],
  },
  inputsTitle: 'Your car deal',
  inputsIntro: 'Use one ownership horizon for every route. The lease inputs are only used in the lease case; the resale assumption is used for cash ownership.',
  fields: [
    { id: 'car_price', label: 'Vehicle price', type: 'number', prefix: '$', value: 38000, min: 0, step: 500 },
    { id: 'down_payment', label: 'Down payment', type: 'number', prefix: '$', value: 5000, min: 0, step: 100 },
    { id: 'trade_equity', label: 'Trade-in equity', type: 'number', prefix: '$', value: 3000, min: 0, step: 100 },
    { id: 'sales_tax_rate', label: 'Sales tax rate', type: 'number', value: 7, min: 0, max: 30, step: 0.1, suffix: '%' },
    { id: 'dealer_fees', label: 'Dealer, title and registration fees', type: 'number', prefix: '$', value: 1800, min: 0, step: 50 },
    { id: 'auto_rate', label: 'Finance APR / interest rate', type: 'number', value: 6.5, min: 0, max: 60, step: 0.01, suffix: '%' },
    { id: 'loan_term_years', label: 'Finance term', type: 'number', value: 5, min: 1, max: 10, step: 1, suffix: 'years' },
    { id: 'lease_months', label: 'Lease length', type: 'number', value: 36, min: 1, max: 84, step: 1, suffix: 'months' },
    { id: 'lease_due', label: 'Lease due at signing', type: 'number', prefix: '$', value: 2500, min: 0, step: 100 },
    { id: 'lease_payment', label: 'Lease monthly payment', type: 'number', prefix: '$', value: 450, min: 0, step: 10 },
    { id: 'lease_buyout', label: 'Lease buyout at end', type: 'number', prefix: '$', value: 22000, min: 0, step: 500 },
    { id: 'resale_value_pct', label: 'Estimated resale value after term', type: 'number', value: 45, min: 0, max: 100, step: 1, suffix: '%' },
    { id: 'annual_maintenance', label: 'Annual maintenance budget', type: 'number', prefix: '$', value: 900, min: 0, step: 50 },
  ],
  fineprint: 'Informational estimate. Dealer quotes, APR, taxes, lease residuals, mileage limits, insurance, fuel and repairs can change the result. Compare the written buyer’s order, financing disclosure or lease worksheet before signing.',
  chart: { type: 'bars', title: 'Three ways to pay for the same car', caption: 'The bars make interest, lease cash and resale assumptions visible alongside the vehicle cost.' },
  breakdownTitle: 'Total-cost breakdown',
  breakdownIntro: 'Compare payment, interest, maintenance and residual value over the same ownership horizon.',
  faq: [
    { q: 'Is leasing cheaper than buying?', a: 'It can have a lower monthly payment, but the answer depends on the lease cash due, term, mileage, fees, buyout and what happens after the lease ends.' },
    { q: 'Why is the monthly payment not enough?', a: 'A payment hides the term, down payment, interest, fees and final value. Two offers with the same payment can have very different total costs.' },
    { q: 'What does APR tell me?', a: 'APR combines the interest rate with certain finance charges and is useful for comparing loan offers. Also review the amount financed, term and total of payments.' },
    { q: 'Should I count resale value?', a: 'Yes for an ownership comparison. The car is an asset with a value you may recover, but resale depends on mileage, condition, market demand and timing.' },
    { q: 'Does the lease calculation include mileage fees?', a: 'Not automatically. Add expected mileage charges or other end-of-lease fees to the lease inputs or your separate budget.' },
    { q: 'What costs are excluded?', a: 'Insurance, fuel, parking, registration renewals, taxes not entered, repairs beyond maintenance and the opportunity cost of cash are excluded.' },
    { q: 'Is a long loan term a good idea?', a: 'It lowers the payment but usually increases interest and can leave the balance above the vehicle value for longer. Compare payoff balance and total payments.' },
    { q: 'When does paying cash make sense?', a: 'Cash avoids interest, but only after considering liquidity, emergency savings and what the money could otherwise do. A lower total cost is not worth losing financial flexibility.' },
  ],
  sources: [
    { name: 'How to compare auto loan offers', url: 'https://www.consumerfinance.gov/ask-cfpb/how-do-i-compare-auto-loan-offers-what-should-i-look-at-besides-the-monthly-payment-en-753/', publisher: 'Consumer Financial Protection Bureau' },
    { name: 'Buying a car', url: 'https://consumer.ftc.gov/articles/buying-car', publisher: 'Federal Trade Commission' },
  ],
  replaces: [],
  lastReviewed: '2026-08-09',
};
