import type { HubData } from '../types';

export const hub: HubData = {
  slug: 'en/cars/import-a-vehicle',
  title: 'Should I import this car? Total vehicle import cost calculator',
  description: 'Estimate the full cost of importing a vehicle after shipping, duty, excise tax, import tax, port charges, compliance and registration.',
  silo: 'Cars',
  siloHref: '/en/cars',
  locale: 'en',
  eyebrow: 'United States · imported vehicles',
  h1: 'Will importing this vehicle actually save me money?',
  lede: 'The purchase price is only the first line. Add freight, duty, excise tax, port charges, compliance work and registration, then compare the result with a local alternative.',
  stamps: ['USD planning estimate', 'On-road cost, not sticker price', '7 calculators inside'],
  resultLabel: 'Estimated imported cost',
  cases: {
    title: 'What is your vehicle decision?',
    intro: 'Use the same vehicle and local-price assumptions across scenarios. The result is a planning screen before you send a deposit or book transport.',
    items: [
      { id: 'import', label: 'I want to import it', hint: 'On-road cost estimate', answer: 'The real import budget combines the vehicle, logistics, border charges, compliance work and registration.', yes: ['Purchase price and transport', 'Duty, excise and import tax', 'Port, broker and compliance charges', 'Registration cost before financing and insurance'], warn: ['Eligibility, safety, emissions and title rules can stop a vehicle from being registered even when the math looks attractive.', 'The estimate does not include financing, maintenance, insurance premiums or exchange-rate movement.'], plazo: 'you verify eligibility and obtain a written all-in quote from the carrier and broker.' },
      { id: 'compare', label: 'I want to compare with buying locally', hint: 'Imported versus local price', answer: 'Importing is financially attractive only when the complete on-road cost is below a comparable local vehicle after risk and delay.', yes: ['A comparable local purchase price', 'Every import tax and fee', 'Compliance and registration work', 'The difference in dollars, not only the percentage'], warn: ['A local vehicle may include a warranty, faster delivery and known service history. Price savings alone do not capture that value.', 'Use the same trim, mileage, condition and required equipment in both prices.'], plazo: 'you can still cancel or renegotiate the purchase if the import quote changes.' },
      { id: 'classic', label: 'I am importing a special or classic vehicle', hint: 'Eligibility first, economics second', answer: 'Special or classic treatment can change eligibility and taxes, but it does not remove the need to document title, condition and compliance.', yes: ['Vehicle value and shipping', 'Any special duty or tax assumption', 'Port and broker costs', 'Registration and inspection budget'], warn: ['Age-based exemptions and state registration rules are jurisdiction-specific. Treat any special rate as a placeholder until confirmed.', 'Restoration, parts, storage and delays can exceed the initial shipping bill.'], plazo: 'the vehicle qualifies under the destination rules and the paperwork is complete.' },
    ],
  },
  inputsTitle: 'Your vehicle import',
  inputsIntro: 'All amounts are in USD. Set a rate to 0 when it does not apply, and use the local price only in the comparison case.',
  fields: [
    { id: 'vehicle_price', label: 'Vehicle purchase price', type: 'number', prefix: '$', value: 28000, min: 0, step: 500 },
    { id: 'vehicle_shipping', label: 'Shipping to destination', type: 'number', prefix: '$', value: 2500, min: 0, step: 100 },
    { id: 'vehicle_insurance', label: 'Transport insurance', type: 'number', prefix: '$', value: 300, min: 0, step: 25 },
    { id: 'vehicle_duty_rate', label: 'Import duty rate', type: 'number', value: 2.5, min: 0, max: 200, step: 0.1, suffix: '%' },
    { id: 'vehicle_excise_rate', label: 'Excise / luxury / environmental tax', type: 'number', value: 0, min: 0, max: 200, step: 0.1, suffix: '%' },
    { id: 'vehicle_vat_rate', label: 'Import VAT / GST rate', type: 'number', value: 0, min: 0, max: 100, step: 0.1, suffix: '%' },
    { id: 'port_fees', label: 'Port, broker and delivery fees', type: 'number', prefix: '$', value: 1800, min: 0, step: 100 },
    { id: 'compliance_cost', label: 'Compliance, inspection and modifications', type: 'number', prefix: '$', value: 2500, min: 0, step: 100 },
    { id: 'registration_cost', label: 'Registration and title costs', type: 'number', prefix: '$', value: 900, min: 0, step: 50 },
    { id: 'local_price', label: 'Comparable local purchase price', type: 'number', prefix: '$', value: 39000, min: 0, step: 500, help: 'Used in the comparison case.' },
  ],
  fineprint: 'Informational estimate. Import eligibility, classification, duty, safety and emissions requirements vary by vehicle, origin, destination and state. Confirm the vehicle with U.S. Customs and Border Protection, NHTSA, EPA and your state motor-vehicle authority before buying.',
  chart: { type: 'bars', title: 'What makes up the import bill', caption: 'Taxes and compliance can outweigh the apparent price gap.' },
  breakdownTitle: 'Import cost layers',
  breakdownIntro: 'Keep the vehicle, border charges and registration separate so a quote can be checked line by line.',
  faq: [
    { q: 'What is the total cost of importing a car?', a: 'It can include the vehicle price, inland transport, ocean or air freight, insurance, duty, excise or environmental taxes, port and broker fees, modifications, inspection, title and registration.' },
    { q: 'Can I import any vehicle into the United States?', a: 'No. Safety, emissions, age, title and eligibility rules apply. A vehicle that cannot be legally imported or registered is not a viable deal regardless of price.' },
    { q: 'Who decides the duty rate?', a: 'The classification, origin and applicable trade measures determine the duty. A customs broker can help confirm the classification, but the importer remains responsible for the entry.' },
    { q: 'Does the calculator include insurance after registration?', a: 'No. It includes transport insurance only. Add the first-year premium to your ownership budget separately.' },
    { q: 'Why compare against a local vehicle?', a: 'A local alternative provides a practical opportunity cost. Compare the same trim, condition, mileage, warranty and required equipment.' },
    { q: 'Are classic cars treated differently?', a: 'Some age-based rules or exemptions may apply, but they are not universal and may change the inspection or registration process. Verify the exact vehicle and state.' },
    { q: 'What delays should I budget for?', a: 'Customs holds, port congestion, missing title documents, modifications, inspection appointments and state registration can all extend the timeline.' },
    { q: 'Can I finance an imported vehicle?', a: 'Some lenders will not finance a vehicle without a domestic title or an established value. Check financing before committing cash to the import.' },
  ],
  sources: [
    { name: 'Importing a vehicle into the United States', url: 'https://www.nhtsa.gov/importing-vehicle', publisher: 'National Highway Traffic Safety Administration' },
    { name: 'Importing into the United States: duties and fees', url: 'https://www.help.cbp.gov/s/article/Article-1225?language=en_US', publisher: 'U.S. Customs and Border Protection' },
  ],
  replaces: [],
  lastReviewed: '2026-08-09',
};
