import type { HubData } from '../types';

export const hub: HubData = {
  slug: 'en/money/insurance-coverage',
  title: 'How much insurance coverage do I need? Life, auto and home calculator',
  description: 'Estimate a starting coverage need for life, auto liability or home property insurance, then compare premiums and the deductible cash you would need.',
  silo: 'Money',
  siloHref: '/en/money',
  locale: 'en',
  eyebrow: 'United States · insurance planning',
  h1: 'How much insurance coverage do I actually need?',
  lede: 'The right limit depends on what would be expensive to replace. Estimate the household income gap, liability exposure or property replacement base, then put premiums and deductible cash beside the coverage number.',
  stamps: ['Starting-point estimate', 'Life, auto and home cases', '7 calculators inside'],
  resultLabel: 'Your coverage starting point',
  cases: {
    title: 'Which policy are you sizing?',
    intro: 'Choose the policy that matters today. The other rows stay visible because a household’s risk budget usually spans life, auto and home coverage.',
    items: [
      { id: 'life', label: 'Life insurance', hint: 'Income and obligations', answer: 'A life-coverage starting point replaces the income and obligations your household would otherwise need to fund, less assets already available.', yes: ['Income to replace and support years', 'Debts and education funding', 'Assets that reduce the gap', 'Premium and deductible context'], warn: ['The right amount depends on beneficiaries, existing coverage, taxes, inflation and the household plan. This is not underwriting.', 'Some policies need medical underwriting and exclusions; compare the actual policy terms.'], plazo: 'the coverage amount is checked against beneficiaries, existing policies and household obligations.' },
      { id: 'auto', label: 'Auto liability', hint: 'Assets and vehicle exposure', answer: 'A higher liability limit can protect more of the household balance sheet, but the legal minimum is not the same as a recommendation.', yes: ['Assets exposed to a claim', 'Vehicle value and use', 'Annual premium', 'Deductible cash before a covered claim'], warn: ['State minimums and policy limits vary. The calculator is a planning starting point, not legal advice or an underwriting quote.', 'Review bodily injury, property damage, uninsured motorist and umbrella coverage together.'], plazo: 'you compare limits and exclusions with the written policy quote.' },
      { id: 'home', label: 'Homeowners property coverage', hint: 'Rebuild cost and contents', answer: 'Home property coverage should start from the cost to rebuild the structure and replace contents, not only the market value of the land and home.', yes: ['Estimated rebuild cost', 'Contents replacement value', 'Annual premium and deductible', 'The gap between insured value and the property base'], warn: ['Replacement cost, dwelling limits, code upgrades, flood, earthquake and other endorsements may be separate.', 'A deductible is cash you must be able to absorb after a covered event.'], plazo: 'the insurer confirms replacement-cost assumptions and policy endorsements.' },
    ],
  },
  inputsTitle: 'Your risk picture',
  inputsIntro: 'Use current USD amounts. The selected case changes which coverage estimate becomes the headline; premiums and deductible remain useful in every case.',
  fields: [
    { id: 'assets', label: 'Assets that could support the household', type: 'number', prefix: '$', value: 150000, min: 0, step: 1000 },
    { id: 'annual_income', label: 'Annual income to protect', type: 'number', prefix: '$', value: 85000, min: 0, step: 1000 },
    { id: 'dependents', label: 'Number of dependents', type: 'number', value: 2, min: 0, max: 20, step: 1 },
    { id: 'support_years', label: 'Years of income support', type: 'number', value: 10, min: 0, max: 50, step: 1 },
    { id: 'debts', label: 'Debts to cover', type: 'number', prefix: '$', value: 260000, min: 0, step: 1000 },
    { id: 'education_fund', label: 'Education or future-care fund', type: 'number', prefix: '$', value: 50000, min: 0, step: 1000 },
    { id: 'auto_value', label: 'Vehicle value / auto exposure', type: 'number', prefix: '$', value: 30000, min: 0, step: 500 },
    { id: 'home_rebuild', label: 'Estimated home rebuild cost', type: 'number', prefix: '$', value: 350000, min: 0, step: 5000 },
    { id: 'contents', label: 'Contents replacement value', type: 'number', prefix: '$', value: 75000, min: 0, step: 1000 },
    { id: 'annual_premium', label: 'Annual premium', type: 'number', prefix: '$', value: 2400, min: 0, step: 50 },
    { id: 'deductible', label: 'Deductible', type: 'number', prefix: '$', value: 2500, min: 0, step: 100 },
  ],
  fineprint: 'Informational estimate. Coverage limits, exclusions, replacement-cost definitions, state requirements and premiums depend on the policy and insurer. Review the quote, declarations page and endorsements with a licensed insurance professional.',
  chart: { type: 'bars', title: 'Coverage need versus cash cost', caption: 'The selected coverage estimate is shown next to five-year premiums and deductible exposure.' },
  breakdownTitle: 'Coverage and premium context',
  breakdownIntro: 'A high coverage limit and a high premium are not interchangeable. Review the selected limit, the recurring premium and the cash deductible separately.',
  faq: [
    { q: 'How much life insurance should I buy?', a: 'A starting point often considers income replacement, debts, future obligations and existing assets. The right amount depends on the household’s actual plan and policy terms.' },
    { q: 'Should auto coverage be higher than the legal minimum?', a: 'Many households compare higher liability limits with their assets and risk tolerance. Legal minimums are a floor, not a personalized recommendation.' },
    { q: 'Is homeowners insurance based on market value?', a: 'Dwelling coverage is generally tied to rebuilding the structure, while market value also includes land, demand and location. Contents and other structures may be separate limits.' },
    { q: 'What is a deductible?', a: 'A deductible is the amount you pay before the insurer pays for a covered claim, subject to policy terms. You should be able to access it without taking on harmful debt.' },
    { q: 'Does a higher deductible always lower the premium?', a: 'It often can, but the relationship depends on the policy and insurer. Compare the premium savings with the additional cash risk.' },
    { q: 'Does this calculate a quote?', a: 'No. It estimates a planning starting point from the numbers you enter. Underwriting, location, claims history, limits and exclusions determine the actual quote.' },
    { q: 'Should I include existing insurance?', a: 'Yes. Subtract existing coverage or assets from the need when reviewing the result; otherwise you may double-count protection.' },
    { q: 'When should I review coverage?', a: 'Review it after marriage, a child, a new home, major debt, a job or income change, a renovation, a vehicle change or a significant asset change.' },
  ],
  sources: [
    { name: 'Consumer insurance information', url: 'https://content.naic.org/consumer', publisher: 'National Association of Insurance Commissioners' },
    { name: 'Life insurance buyer resources', url: 'https://content.naic.org/consumer/life-insurance', publisher: 'National Association of Insurance Commissioners' },
  ],
  replaces: [],
  lastReviewed: '2026-08-09',
};
