import type { HubData } from '../types';

export const hub: HubData = {
  slug: 'en/money/landed-cost',
  title: 'How much will this import really cost? Landed cost calculator',
  description: 'Estimate the real cost of an imported product after freight, insurance, duty, import tax and handling fees — then test a resale margin.',
  silo: 'Money',
  siloHref: '/en/money',
  locale: 'en',
  eyebrow: 'United States · importing and resale margins',
  h1: 'What will this imported product really cost me?',
  lede: 'A low product price can hide freight, customs duty, import tax and carrier fees. Put every layer in one place, then switch to the resale case to see whether the margin survives.',
  stamps: ['USD planning estimate', 'Duty and tax rates stay editable', '7 calculators inside'],
  resultLabel: 'Your estimated landed cost',
  cases: {
    title: 'What are you using the estimate for?',
    intro: 'Choose the decision you are making. The same shipment can look affordable for personal use and unprofitable when marketplace fees are added.',
    items: [
      { id: 'purchase', label: 'I am buying for myself', hint: 'Total delivered cost', answer: 'Landed cost is the product, freight and insurance plus the import charges and fees required to get it to you.', yes: ['Product price and shipping terms', 'The customs value used for the duty estimate', 'Duty, import VAT or GST and broker fees', 'Total shipment cost and cost per unit'], warn: ['This is a planning estimate, not a customs ruling. The classification, origin and destination can change the final bill.', 'Sales tax charged after import, storage, demurrage and returns are not included unless you enter them as fees.'], plazo: 'the carrier or customs broker gives you the final assessment before release.' },
      { id: 'resale', label: 'I am importing to resell', hint: 'Gross profit after marketplace fees', answer: 'A resale margin is only real after landed cost and the selling platform fee are deducted from the sale price.', yes: ['Shipment cost per unit', 'Marketplace fee as a percentage of sales', 'Revenue for the entered quantity', 'Estimated gross profit before income tax and fixed overhead'], warn: ['Gross profit is not net profit: add storage, fulfillment, returns, advertising and your own labor before committing inventory.', 'Use the platform fee schedule for your category and country; payment processing and shipping to the customer may be separate.'], plazo: 'you can compare the result with your minimum margin before placing the purchase order.' },
      { id: 'compare', label: 'I am comparing suppliers', hint: 'One complete cost basis', answer: 'The cheapest quote is not necessarily the cheapest shipment once freight, duty and fixed fees are spread across the units.', yes: ['The same quantity and Incoterm for each supplier', 'Freight and insurance for each quote', 'The duty and import-tax assumptions', 'Cost per unit on a like-for-like basis'], warn: ['Do not compare an all-in quote with a product-only quote. Ask what customs clearance and delivery charges are included.', 'A larger order can lower cost per unit but increases cash tied up in inventory.'], plazo: 'the quote validity window closes, because freight and exchange rates can move.' },
    ],
  },
  inputsTitle: 'Your shipment',
  inputsIntro: 'Enter USD amounts and rates. If a charge is already included in your supplier quote, leave it out so you do not count it twice.',
  fields: [
    { id: 'product_value', label: 'Product value', type: 'number', prefix: '$', value: 2500, min: 0, step: 50, help: 'The price of the goods before freight and insurance.' },
    { id: 'shipping', label: 'Freight and shipping', type: 'number', prefix: '$', value: 350, min: 0, step: 25, help: 'Transport to the destination port, airport or delivery address.' },
    { id: 'insurance', label: 'Cargo insurance', type: 'number', prefix: '$', value: 40, min: 0, step: 10 },
    { id: 'duty_rate', label: 'Import duty rate', type: 'number', value: 5, min: 0, max: 100, step: 0.1, suffix: '%', help: 'Use the rate for the product classification and origin.' },
    { id: 'vat_rate', label: 'Import VAT / GST rate', type: 'number', value: 0, min: 0, max: 100, step: 0.1, suffix: '%', help: 'Enter 0 if your destination does not charge this at import or if it is recoverable for your business.' },
    { id: 'fees', label: 'Broker, carrier and processing fees', type: 'number', prefix: '$', value: 125, min: 0, step: 10 },
    { id: 'quantity', label: 'Units in the shipment', type: 'number', value: 20, min: 1, max: 100000, step: 1 },
    { id: 'selling_price', label: 'Selling price per unit', type: 'number', prefix: '$', value: 225, min: 0, step: 5, help: 'Used in the resale case.' },
    { id: 'marketplace_rate', label: 'Marketplace fee', type: 'number', value: 12, min: 0, max: 100, step: 0.1, suffix: '%', help: 'Used in the resale case.' },
  ],
  fineprint: 'Informational estimate. Customs classification, origin rules, de minimis treatment, tax recovery and carrier charges can change the final amount. Confirm the shipment with the destination customs authority or a licensed broker.',
  chart: { type: 'bars', title: 'Where the shipment cost goes', caption: 'The bars separate the goods and logistics from import charges and fixed fees.' },
  breakdownTitle: 'Cost layers',
  breakdownIntro: 'The result keeps the customs value, tax layers and fixed charges visible so you can audit the quote.',
  faq: [
    { q: 'What is landed cost?', a: 'Landed cost is the total cost to get imported goods to their destination: product price, freight, insurance, duty, import taxes and applicable handling fees.' },
    { q: 'Is shipping included in customs value?', a: 'It often is, together with insurance, but the exact valuation rule depends on the destination and the transaction terms. Confirm the local rule before filing.' },
    { q: 'Why can the cheapest supplier be more expensive?', a: 'A product-only quote can become more expensive after freight, duty and fixed clearance charges. Compare cost per unit after every required charge.' },
    { q: 'Does this include U.S. sales tax?', a: 'No. Sales tax charged on a later retail sale is different from import duty and import tax. Add it to fees if you need a conservative planning view.' },
    { q: 'Can a business recover import VAT or GST?', a: 'Sometimes a registered business can claim eligible import tax as an input credit, but eligibility and paperwork vary. Do not treat it as recoverable without confirming the rule.' },
    { q: 'What is the difference between duty and a tariff?', a: 'In everyday importing language they are often used interchangeably. The applicable percentage is determined by classification, origin and trade measures.' },
    { q: 'Should I calculate per shipment or per unit?', a: 'Both. Per shipment tells you the cash commitment; per unit tells you the minimum price or margin needed to resell.' },
    { q: 'What charges are commonly missed?', a: 'Brokerage, port handling, storage, inspection, demurrage, domestic delivery, payment fees and returns are frequent omissions. Put uncertain charges into the fees field.' },
  ],
  sources: [
    { name: 'Importing into the United States: duties and fees', url: 'https://www.help.cbp.gov/s/article/Article-1225?language=en_US', publisher: 'U.S. Customs and Border Protection' },
    { name: 'Harmonized System overview', url: 'https://www.wcoomd.org/en/topics/nomenclature/overview/what-is-the-harmonized-system.aspx', publisher: 'World Customs Organization' },
  ],
  replaces: [],
  lastReviewed: '2026-08-09',
};
