import type { HubData } from '../types';

export const hub: HubData = {
  slug: 'en/health/medical-out-of-pocket',
  title: 'How much will health insurance cost me? Premium and out-of-pocket calculator',
  description: 'Estimate annual health-plan cost from premiums, deductible, coinsurance, copays and out-of-pocket maximum, then compare two plans.',
  silo: 'Health',
  siloHref: '/en/health',
  locale: 'en',
  eyebrow: 'United States · health-plan costs',
  h1: 'How much will this health plan really cost me?',
  lede: 'The premium is only the predictable part. Model expected covered care, deductible, coinsurance, copays and the out-of-pocket maximum, then compare a second plan under the same usage assumption.',
  stamps: ['Annual USD estimate', 'In-network covered care assumption', '7 calculators inside'],
  resultLabel: 'Estimated annual health cost',
  cases: {
    title: 'What cost scenario are you planning for?',
    intro: 'Start with normal expected care, compare two plans or stress-test the annual maximum. The result is designed to make the trade-off visible before enrollment.',
    items: [
      { id: 'annual', label: 'I want my expected annual cost', hint: 'Premium plus care', answer: 'Annual health cost combines twelve months of premiums with your estimated covered in-network cost sharing, subject to the plan maximum.', yes: ['Annual premium', 'Deductible and coinsurance', 'Copays and expected covered care', 'Out-of-pocket maximum'], warn: ['The result assumes covered in-network care and does not estimate premiums for every household member unless you include them.', 'Non-covered services, balance billing, travel care and out-of-network costs can be different.'], plazo: 'you compare the estimate with the plan’s Summary of Benefits and Coverage.' },
      { id: 'compare', label: 'I am comparing two plans', hint: 'Lower-cost scenario', answer: 'The better plan depends on your expected use: a lower premium can lose its advantage when deductible and coinsurance rise.', yes: ['Plan A premium and cost sharing', 'Plan B premium and cost sharing', 'The same expected care for both plans', 'The annual difference under the entered scenario'], warn: ['Do not compare a low-premium plan with a richer plan using different care assumptions.', 'Network, drug formulary, referrals, HSA rules and employer contributions can change the decision.'], plazo: 'you confirm the network, prescriptions and employer contribution before enrolling.' },
      { id: 'worst', label: 'I want the worst-case budget', hint: 'Premium plus maximum exposure', answer: 'A conservative annual budget uses twelve months of premium plus the plan’s in-network out-of-pocket maximum, subject to plan terms.', yes: ['Annual premium', 'Out-of-pocket maximum', 'The cash reserve needed for a bad covered year', 'The gap between expected and worst-case cost'], warn: ['The maximum usually excludes premiums and some non-covered or out-of-network expenses. Read the plan definition.', 'A maximum is not a promise that every service or provider is covered.'], plazo: 'your emergency reserve can absorb the premium plus the plan’s actual maximum.' },
    ],
  },
  inputsTitle: 'Your health-plan numbers',
  inputsIntro: 'Enter monthly premiums and covered in-network care for one year. The second-plan fields are used in the comparison case; set them to 0 if you are reviewing only Plan A.',
  fields: [
    { id: 'annual_premium', label: 'Plan A monthly premium', type: 'number', prefix: '$', value: 450, min: 0, step: 10 },
    { id: 'deductible', label: 'Plan A deductible', type: 'number', prefix: '$', value: 1800, min: 0, step: 50 },
    { id: 'coinsurance', label: 'Plan A coinsurance', type: 'number', value: 20, min: 0, max: 100, step: 1, suffix: '%' },
    { id: 'copays', label: 'Expected annual copays', type: 'number', prefix: '$', value: 600, min: 0, step: 25 },
    { id: 'oop_max', label: 'Plan A out-of-pocket maximum', type: 'number', prefix: '$', value: 8700, min: 0, step: 100 },
    { id: 'covered_spend', label: 'Expected covered care billed amount', type: 'number', prefix: '$', value: 6000, min: 0, step: 100 },
    { id: 'second_premium', label: 'Plan B monthly premium', type: 'number', prefix: '$', value: 280, min: 0, step: 10 },
    { id: 'second_deductible', label: 'Plan B deductible', type: 'number', prefix: '$', value: 4500, min: 0, step: 50 },
    { id: 'second_coinsurance', label: 'Plan B coinsurance', type: 'number', value: 30, min: 0, max: 100, step: 1, suffix: '%' },
    { id: 'second_oop_max', label: 'Plan B out-of-pocket maximum', type: 'number', prefix: '$', value: 9500, min: 0, step: 100 },
  ],
  fineprint: 'Informational estimate. This assumes covered in-network care and simplified cost sharing. Premium tax credits, employer contributions, prescriptions, provider networks, non-covered services and plan-specific rules can change the actual cost. Review the Summary of Benefits and Coverage.',
  chart: { type: 'bars', title: 'Premiums versus cost sharing', caption: 'Compare the predictable premium with the deductible, coinsurance, copays and maximum exposure.' },
  breakdownTitle: 'Annual cost layers',
  breakdownIntro: 'The plan’s annual cost is premium plus covered care you pay, capped by the entered in-network maximum. The maximum does not normally include premium.',
  faq: [
    { q: 'What is the total cost of health insurance?', a: 'For planning, add twelve months of premium to the covered care you pay through deductible, coinsurance and copays. The plan’s in-network out-of-pocket maximum limits many, but not all, covered expenses.' },
    { q: 'Does the out-of-pocket maximum include premiums?', a: 'Usually no. Premiums are generally separate from the out-of-pocket maximum, which is why a bad-year budget often adds annual premiums to the maximum.' },
    { q: 'What is a deductible?', a: 'A deductible is the amount you generally pay for covered services before the plan begins paying according to its cost-sharing rules, subject to plan exceptions.' },
    { q: 'What is coinsurance?', a: 'Coinsurance is the percentage of the allowed amount you pay after applicable deductible rules. The plan pays the remaining percentage until the out-of-pocket rules apply.' },
    { q: 'Why can a low premium plan cost more?', a: 'A low premium may come with a higher deductible, coinsurance or out-of-pocket maximum. Compare the total under both low-use and high-use scenarios.' },
    { q: 'Does this include out-of-network care?', a: 'No. The estimate is for covered in-network care. Out-of-network benefits, balance billing and non-covered care can create additional exposure.' },
    { q: 'What is the Summary of Benefits and Coverage?', a: 'It is a standardized document that helps compare a plan’s premiums, deductibles, cost sharing and examples of coverage. Use it with the network and formulary information.' },
    { q: 'Should I include employer contributions?', a: 'Yes. Subtract employer or marketplace contributions from the premium you actually pay before comparing your household cost.' },
  ],
  sources: [
    { name: 'Your total costs for health care', url: 'https://www.healthcare.gov/choose-a-plan/your-total-costs/', publisher: 'HealthCare.gov' },
    { name: 'Out-of-pocket maximum', url: 'https://www.healthcare.gov/glossary/out-of-pocket-maximum-limit/', publisher: 'HealthCare.gov' },
  ],
  replaces: [],
  lastReviewed: '2026-08-09',
};
