import type { HubData } from '../types';

export const hub: HubData = {
  slug: 'en/life/move-abroad',
  title: 'Can I afford to move abroad? International relocation calculator',
  description: 'Compare take-home pay, monthly living costs, one-time relocation costs and the first-year or five-year financial position of moving abroad.',
  silo: 'Life',
  siloHref: '/en/life',
  locale: 'en',
  eyebrow: 'International · relocation planning',
  h1: 'Can I afford to move abroad?',
  lede: 'Moving countries is a cash-flow decision before it is a lifestyle decision. Estimate take-home pay, recurring costs, the income gap and the one-time bill, then see what remains after year one.',
  stamps: ['USD planning estimate', 'Destination costs are user inputs', '7 calculators inside'],
  resultLabel: 'Your move position',
  cases: {
    title: 'What kind of move are you planning?',
    intro: 'Use a work move, a five-year commitment or a retirement move as the frame. The inputs stay editable because city, household and benefits matter more than a country average.',
    items: [
      { id: 'job', label: 'I am moving for a job', hint: 'First-year cash flow', answer: 'A job move works when the after-tax income covers the new monthly budget and the one-time transition costs.', yes: ['Host-country gross income and tax assumption', 'Rent, living costs and healthcare', 'Home-country costs that remain active', 'Income-gap months and relocation costs'], warn: ['Compare benefits, health coverage, pension contributions and paid leave, not salary alone.', 'A signing bonus or employer relocation package can change year one; enter it as a negative relocation cost if applicable.'], plazo: 'the offer letter and benefits are final enough to compare against your current cash flow.' },
      { id: 'five-year', label: 'I want to commit for five years', hint: 'Longer-term position', answer: 'A five-year view shows whether the monthly surplus has enough time to overcome the move bill and income gap.', yes: ['Monthly surplus after destination and home-country costs', 'Upfront move and visa costs', 'Five-year net position', 'The recurring cost that is putting pressure on the plan'], warn: ['This is not an investment forecast: it excludes salary growth, exchange-rate changes, investment returns and major medical events.', 'Do not treat a positive five-year total as proof that a visa or tax status is available.'], plazo: 'you can compare the five-year horizon with the visa, contract and family plan.' },
      { id: 'retire', label: 'I am moving for retirement', hint: 'Year-one affordability', answer: 'A retirement move needs a durable monthly surplus, a healthcare reserve and enough cash to absorb the relocation period.', yes: ['Reliable monthly income after tax', 'Housing, daily living and healthcare', 'Home-country obligations', 'Move costs and income-gap reserve'], warn: ['Healthcare premiums and out-of-pocket costs can rise with age; test a higher health budget before relying on the result.', 'Pension, social-security, currency and residency rules need official confirmation.'], plazo: 'your income, insurance and residency arrangements are documented for the destination.' },
    ],
  },
  inputsTitle: 'Your destination budget',
  inputsIntro: 'Use monthly USD amounts for recurring costs. Enter the host-country tax rate as a rough planning assumption, then verify the actual net pay in the offer or pension documents.',
  fields: [
    { id: 'annual_gross', label: 'Annual gross income in the destination', type: 'number', prefix: '$', value: 90000, min: 0, step: 1000 },
    { id: 'host_tax_rate', label: 'Estimated host-country tax rate', type: 'number', value: 25, min: 0, max: 100, step: 0.5, suffix: '%' },
    { id: 'monthly_rent', label: 'Monthly rent or housing cost', type: 'number', prefix: '$', value: 2200, min: 0, step: 50 },
    { id: 'monthly_living', label: 'Monthly food, transport and living costs', type: 'number', prefix: '$', value: 1600, min: 0, step: 50 },
    { id: 'monthly_health', label: 'Monthly healthcare and insurance', type: 'number', prefix: '$', value: 500, min: 0, step: 25 },
    { id: 'home_country_costs', label: 'Monthly costs kept in your home country', type: 'number', prefix: '$', value: 700, min: 0, step: 25 },
    { id: 'relocation_cost', label: 'One-time relocation cost', type: 'number', prefix: '$', value: 10000, min: 0, step: 250, help: 'Flights, deposits, shipping, temporary housing and setup.' },
    { id: 'visa_cost', label: 'Visa, legal and document costs', type: 'number', prefix: '$', value: 2500, min: 0, step: 100 },
    { id: 'income_gap_months', label: 'Months without normal income', type: 'number', value: 2, min: 0, max: 24, step: 1 },
  ],
  fineprint: 'Informational estimate. Immigration, tax residency, pension, healthcare and employment rules are country-specific. Confirm the destination requirements with official authorities and a qualified adviser.',
  chart: { type: 'bars', title: 'Monthly destination cash flow', caption: 'Take-home pay is shown against recurring costs; one-time move costs are kept separate.' },
  breakdownTitle: 'Move economics',
  breakdownIntro: 'The result separates recurring affordability from the transition reserve that must be available before the move.',
  faq: [
    { q: 'How much money should I save before moving abroad?', a: 'There is no universal number. A useful starting point is the one-time move bill plus the months of income gap and an emergency reserve sized to your destination budget.' },
    { q: 'Should I compare gross or net salary?', a: 'Compare net salary after taxes, mandatory contributions, health deductions and any benefit changes. Gross salary can hide a large difference in usable cash.' },
    { q: 'What costs are easy to miss when relocating?', a: 'Deposits, temporary housing, shipping, flights, document legalization, visa fees, healthcare setup, school costs and duplicate home-country bills are common omissions.' },
    { q: 'Should I keep paying costs in my home country?', a: 'Many movers keep a mortgage, storage, family support, subscriptions or insurance. Enter those recurring obligations separately instead of assuming they disappear.' },
    { q: 'Does the result include exchange-rate risk?', a: 'No. The calculator uses USD inputs. Test a weaker destination currency or add a monthly buffer if your income and obligations use different currencies.' },
    { q: 'Is a positive monthly surplus enough to move?', a: 'Not by itself. Check visa eligibility, employment rights, health coverage, tax residency, emergency savings and the reliability of the income.' },
    { q: 'How should retirees use the calculator?', a: 'Use reliable after-tax pension or portfolio income, then stress-test healthcare, rent and currency assumptions. Avoid counting uncertain investment returns as monthly income.' },
    { q: 'When should I use the five-year case?', a: 'Use it when the decision involves a contract, visa or family commitment lasting several years. It shows whether the upfront cost is recovered over time, not whether the move is legally possible.' },
  ],
  sources: [
    { name: 'Cost of living data', url: 'https://www.numbeo.com/cost-of-living/', publisher: 'Numbeo' },
    { name: 'International travel and relocation information', url: 'https://travel.state.gov/content/travel/en/international-travel.html', publisher: 'U.S. Department of State' },
  ],
  replaces: [],
  lastReviewed: '2026-08-09',
};
