import type { HubData } from '../types';

export const hub: HubData = {
  slug: 'en/money/student-loans',
  title: 'Student loan payment, payoff and extra-payment calculator',
  description: 'Compare a scheduled student-loan payment, total interest, an extra monthly payment and an income-based planning scenario in one place.',
  silo: 'Money',
  siloHref: '/en/money',
  locale: 'en',
  eyebrow: 'United States · student loan planning',
  h1: 'What will my student loan really cost to repay?',
  lede: 'Monthly payment is only one part of the decision. Estimate the scheduled payment and total interest, then test how an extra payment or an income-based assumption changes the path.',
  stamps: ['Fixed-rate amortization estimate', 'Income case is a planning proxy', '7 calculators inside'],
  resultLabel: 'Your student-loan scenario',
  cases: {
    title: 'Which student-loan decision are you making?',
    intro: 'Start with the scheduled plan, then switch to extra payments or an income-based planning screen. Compare official plan terms before enrolling.',
    items: [
      { id: 'standard', label: 'I want the normal repayment math', hint: 'Payment and total interest', answer: 'A fixed repayment estimate shows the monthly payment, payoff horizon and interest cost if the rate and term stay unchanged.', yes: ['Current balance, rate and term', 'Monthly payment estimate', 'Total interest over the schedule', 'A baseline for comparing alternatives'], warn: ['Federal plan payments, capitalization, servicer rules and forgiveness can differ from a simple fixed-rate loan.', 'Use your official loan details and StudentAid plan information for the decision.'], plazo: 'you compare the estimate with your servicer statement and official repayment-plan terms.' },
      { id: 'extra', label: 'I can pay extra each month', hint: 'Interest and time saved', answer: 'An extra principal payment can shorten a fixed schedule and reduce interest, but only if the servicer applies it as instructed.', yes: ['Extra amount per month', 'Months removed from the schedule', 'Interest avoided', 'The baseline payment for cash-flow comparison'], warn: ['Check for prepayment rules and tell the servicer how extra money should be applied.', 'Keep an emergency fund and capture any employer match before sending every spare dollar to debt.'], plazo: 'the servicer confirms the extra payment will reduce principal rather than advance the due date.' },
      { id: 'income', label: 'I need an income-based planning view', hint: 'Payment against income', answer: 'An income-based payment screen can show affordability, but the official formula depends on the specific federal or private plan and your documented circumstances.', yes: ['Annual income and family size', 'An entered income exemption', 'An entered payment percentage', 'A rough monthly payment and interest path'], warn: ['This is not an eligibility or forgiveness calculator. Official income-driven plans use specific definitions, certifications and rules.', 'A lower payment can increase the time and interest needed to repay.'], plazo: 'you submit the official income and family information and review the plan disclosure.' },
    ],
  },
  inputsTitle: 'Your loan details',
  inputsIntro: 'Use the current principal and note rate from your statement. The income fields are only used for the planning case and do not determine official eligibility.',
  fields: [
    { id: 'loan_balance', label: 'Current loan balance', type: 'number', prefix: '$', value: 35000, min: 0, step: 100 },
    { id: 'loan_rate', label: 'Annual interest rate', type: 'number', value: 5.5, min: 0, max: 60, step: 0.01, suffix: '%' },
    { id: 'loan_term_years', label: 'Remaining repayment term', type: 'number', value: 10, min: 1, max: 40, step: 1, suffix: 'years' },
    { id: 'extra_monthly', label: 'Extra payment each month', type: 'number', prefix: '$', value: 150, min: 0, step: 25 },
    { id: 'annual_income', label: 'Annual income for planning case', type: 'number', prefix: '$', value: 65000, min: 0, step: 1000 },
    { id: 'family_size', label: 'Family size', type: 'number', value: 1, min: 1, max: 20, step: 1 },
    { id: 'income_exemption', label: 'Income exemption per person', type: 'number', prefix: '$', value: 30000, min: 0, step: 500 },
    { id: 'income_payment_pct', label: 'Income payment percentage', type: 'number', value: 10, min: 0, max: 100, step: 0.5, suffix: '%' },
  ],
  fineprint: 'Informational estimate. Federal and private student-loan repayment plans have their own definitions, certifications, capitalization rules, forgiveness provisions and servicer practices. Check StudentAid.gov and your loan documents before acting.',
  chart: { type: 'bars', title: 'Principal versus interest', caption: 'The baseline shows how much of the entered schedule is principal, interest and potential interest avoided.' },
  breakdownTitle: 'Repayment breakdown',
  breakdownIntro: 'Use the scheduled case as a baseline, then compare the cash-flow and interest effect of an extra or income-based scenario.',
  faq: [
    { q: 'How is a student-loan payment calculated?', a: 'A fixed-rate amortizing payment depends on the balance, annual interest rate and number of monthly payments. Real plans can add rules that a simple formula does not capture.' },
    { q: 'Does paying extra reduce interest?', a: 'Usually, reducing principal earlier reduces the balance on which future interest accrues. Confirm that the servicer applies the extra amount to principal.' },
    { q: 'Can I pay off student loans early?', a: 'Many federal and private loans allow early repayment without a prepayment penalty, but check the specific loan agreement and servicer instructions.' },
    { q: 'Is the income-based result an official payment?', a: 'No. It is a transparent planning proxy using your entered income, family size, exemption and percentage. Official plans use their own formula and documentation.' },
    { q: 'Why can a lower monthly payment cost more?', a: 'A lower payment can stretch repayment over more time, allowing interest to accrue for longer. Compare total interest and payoff date, not payment alone.' },
    { q: 'Does this include loan forgiveness?', a: 'No. Forgiveness depends on the plan, employer, payment history, certification, qualifying employment and rules that can change.' },
    { q: 'Should I refinance federal student loans?', a: 'Compare the rate reduction with the federal protections you may give up, such as income-driven options, deferment or forgiveness pathways.' },
    { q: 'Where can I check my official options?', a: 'Use your servicer statement and the U.S. Department of Education’s StudentAid.gov tools and plan information.' },
  ],
  sources: [
    { name: 'Compare student loan repayment plans', url: 'https://studentaid.gov/articles/compare-student-loan-repayment-plans-calculator/', publisher: 'Federal Student Aid' },
    { name: 'Student loan repayment information', url: 'https://studentaid.gov/manage-loans/repayment', publisher: 'Federal Student Aid' },
  ],
  replaces: [],
  lastReviewed: '2026-08-09',
};
