import type { HubData } from '../types';

export const hub: HubData = {
  slug: 'en/money/tax-residency',
  title: 'Am I a tax resident? Day-count and foreign-income planning calculator',
  description: 'Organize current-year and prior-year days, test a weighted presence threshold and estimate the tax-rate difference on foreign income.',
  silo: 'Money',
  siloHref: '/en/money',
  locale: 'en',
  eyebrow: 'United States · international tax planning',
  h1: 'Am I a tax resident in the United States or abroad?',
  lede: 'Day counts are only one part of residency, but they are a useful first screen. Put your travel days in one place, test the entered thresholds and model a rough foreign-income difference before seeking professional advice.',
  stamps: ['Planning screen, not a tax filing', 'Day-count tests are editable', '7 calculators inside'],
  resultLabel: 'Your entered residency test',
  cases: {
    title: 'Which residency question are you testing?',
    intro: 'Select the frame that matches your situation. A day-count result is a prompt for document review, not a legal conclusion.',
    items: [
      { id: 'us', label: 'U.S. substantial-presence planning', hint: 'Current and prior-year days', answer: 'The U.S. substantial presence test uses current-year days plus a fraction of days in the two preceding years, subject to exceptions.', yes: ['Current-year days', 'Prior-year day counts', 'The current-year minimum and weighted threshold', 'A record you can reconcile with travel documents'], warn: ['The IRS test has exceptions and special rules. Passing or failing this screen does not determine your filing status by itself.', 'Use passport stamps, travel records and employer or visa records rather than memory.'], plazo: 'you review the official test and exceptions before filing or changing withholding.' },
      { id: 'feie', label: 'Foreign earned income planning', hint: '330-day physical presence screen', answer: 'The physical-presence test for the foreign earned income exclusion is based on 330 full days in a foreign country or countries during a 12-month period, with additional requirements.', yes: ['Foreign physical-presence days', 'The entered 330-day threshold', 'Foreign earned income', 'A rough tax-rate difference for planning'], warn: ['The exclusion has qualification, source, housing and documentation rules. This estimate does not calculate the exclusion or tax return.', 'A tax treaty, bona fide residence, employer location and the type of income can change the result.'], plazo: 'you confirm the 12-month period, qualifying income and documentation with the official guidance.' },
      { id: 'host', label: 'I may be resident in the host country', hint: 'Threshold comparison', answer: 'Many countries use a day threshold, ties or a combination of tests. Use the fields as a checklist for the rule you are researching.', yes: ['The threshold you want to test', 'Current and prior-year presence', 'Foreign days and income', 'A rough home-versus-host rate comparison'], warn: ['Do not copy another country’s threshold into a filing decision. Residency rules differ and often include a home, family, economic-ties or habitual-abode test.', 'If two countries claim residence, treaty tie-breaker rules may apply.'], plazo: 'the host authority or adviser confirms the exact test and treaty position.' },
    ],
  },
  inputsTitle: 'Your day count and income',
  inputsIntro: 'Enter days from reliable travel records. The threshold fields are editable so you can model the official test you are researching without hard-coding a legal conclusion.',
  fields: [
    { id: 'current_days', label: 'Current-year days in the country', type: 'number', value: 120, min: 0, max: 366, step: 1 },
    { id: 'previous_days', label: 'Prior-year days', type: 'number', value: 90, min: 0, max: 366, step: 1 },
    { id: 'older_days', label: 'Days two years ago', type: 'number', value: 60, min: 0, max: 366, step: 1 },
    { id: 'current_minimum_days', label: 'Current-year minimum for the test', type: 'number', value: 31, min: 0, max: 366, step: 1, help: 'Change this only to match the official rule you are researching.' },
    { id: 'residency_threshold', label: 'Weighted residency threshold', type: 'number', value: 183, min: 0, max: 1000, step: 1 },
    { id: 'foreign_days', label: 'Full foreign-country days', type: 'number', value: 280, min: 0, max: 366, step: 1 },
    { id: 'foreign_threshold', label: 'Foreign physical-presence threshold', type: 'number', value: 330, min: 0, max: 366, step: 1 },
    { id: 'foreign_income', label: 'Foreign earned income', type: 'number', prefix: '$', value: 80000, min: 0, step: 1000 },
    { id: 'home_tax_rate', label: 'Home-country tax assumption', type: 'number', value: 30, min: 0, max: 100, step: 0.5, suffix: '%' },
    { id: 'host_tax_rate', label: 'Host-country tax assumption', type: 'number', value: 20, min: 0, max: 100, step: 0.5, suffix: '%' },
  ],
  fineprint: 'Informational estimate only. Tax residence, treaty tie-breakers, filing status, exclusions and credits depend on facts and official rules. Keep a travel log and consult the IRS, the host authority or a qualified tax professional before filing.',
  chart: { type: 'bars', title: 'Your entered day-count signals', caption: 'The bars show current-year days, the weighted test and foreign physical-presence days.' },
  breakdownTitle: 'Residency signals',
  breakdownIntro: 'Use each row as a document checklist. The thresholds are assumptions you can change to match the official rule.',
  faq: [
    { q: 'What is tax residency?', a: 'Tax residency is the status a country assigns under its domestic rules, often affecting where income is reported. It is not always the same as citizenship, immigration status or domicile.' },
    { q: 'How does the U.S. substantial presence test work?', a: 'The test generally combines current-year days with one-third of prior-year days and one-sixth of days two years earlier, plus a current-year minimum and exceptions.' },
    { q: 'What is the 330-day test?', a: 'The physical-presence test for the foreign earned income exclusion generally requires 330 full days in a foreign country or countries during a qualifying 12-month period, alongside other requirements.' },
    { q: 'Do travel days count as full days abroad?', a: 'The exact treatment depends on the test and the facts. Keep records of arrival and departure times and check the official instructions rather than assuming every travel day qualifies.' },
    { q: 'Can two countries both consider me resident?', a: 'Yes. Domestic rules can overlap. A treaty may provide tie-breaker rules, but the analysis depends on facts such as a permanent home, center of vital interests and habitual abode.' },
    { q: 'Does this calculate my tax bill?', a: 'No. It tests entered day-count assumptions and shows a rough rate difference on income. Deductions, credits, source rules, treaty relief and exclusions are not calculated.' },
    { q: 'What records should I keep?', a: 'Keep passport and border records, tickets, calendars, leases, utility bills, employment documents, visa records and a contemporaneous travel log.' },
    { q: 'Should I use this before moving?', a: 'Yes, as a checklist for questions. Use official guidance and professional advice before changing withholding, ending a lease, filing or claiming an exclusion.' },
  ],
  sources: [
    { name: 'Substantial Presence Test', url: 'https://www.irs.gov/individuals/international-taxpayers/substantial-presence-test', publisher: 'Internal Revenue Service' },
    { name: 'Foreign Earned Income Exclusion: Physical Presence Test', url: 'https://www.stayexempt.irs.gov/individuals/international-taxpayers/foreign-earned-income-exclusion-physical-presence-test', publisher: 'Internal Revenue Service' },
  ],
  replaces: [],
  lastReviewed: '2026-08-09',
};
