#!/usr/bin/env python3
"""
Extrae los redirects de pruning batch 1 + 2 desde public/_redirects y
genera src/lib/pruning-redirects.ts con una Map para usar en el middleware.

¿Por qué?
  CF Workers Static Assets sirve el HTML del archivo antes de aplicar el
  `_redirects` si el archivo existe en dist/. Para forzar el 301 sin
  borrar JSONs de las calcs (que perdería link equity si nos arrepentimos),
  hacemos el redirect en el middleware Astro (corre antes que assets).

Política de regeneración:
  Correr después de agregar un nuevo "# Pruning batch N" en _redirects.
  Output se commitea junto con el cambio del _redirects.

Idempotente. No modifica _redirects, solo lo lee.
"""
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
REDIRECTS_FILE = ROOT / 'public' / '_redirects'
OUTPUT_TS = ROOT / 'src' / 'lib' / 'pruning-redirects.ts'


def main() -> int:
    redirects = {}
    section = None
    for line in REDIRECTS_FILE.read_text(encoding='utf-8').split('\n'):
        line = line.strip()
        if line.startswith('# Pruning batch'):
            section = line
            continue
        if line.startswith('#') or not line:
            continue
        if not section:
            continue
        if not line.startswith('/'):
            continue
        parts = line.split()
        if len(parts) < 3:
            continue
        src, dst = parts[0], parts[1]
        redirects[src] = dst

    lines = [
        '// Generated by scripts/extract-pruning-redirects.py — DO NOT EDIT MANUALLY',
        '// Pruning batch 1+ redirects para CF Workers middleware.',
        '//',
        '// Razón: _redirects no aplica si el archivo HTML existe en dist/',
        '// (CF Workers Static Assets lo sirve antes). Middleware corre antes',
        '// que assets → soluciona sin necesidad de borrar JSONs.',
        '',
        'export const PRUNING_REDIRECTS: Record<string, string> = {',
    ]
    for src in sorted(redirects.keys()):
        # JS-safe quoting (los slugs no tienen caracteres especiales pero por las dudas)
        src_q = "'" + src.replace("'", "\\'") + "'"
        dst_q = "'" + redirects[src].replace("'", "\\'") + "'"
        lines.append(f'  {src_q}: {dst_q},')
    lines.append('};')
    lines.append('')

    OUTPUT_TS.write_text('\n'.join(lines), encoding='utf-8')
    print(f'✓ Generado: {OUTPUT_TS.relative_to(ROOT)} ({len(redirects)} entries)')
    return 0


if __name__ == '__main__':
    import sys
    sys.exit(main())
