#!/usr/bin/env python3
"""
Extrae los redirects de pruning batch 1 + 2 desde public/_redirects y
genera src/lib/pruning-redirects.ts con una Map para usar en el middleware.

¿Por qué?
  CF Workers Static Assets sirve el HTML del archivo antes de aplicar el
  `_redirects` si el archivo existe en dist/. Para forzar el 301 sin
  borrar JSONs de las calcs (que perdería link equity si nos arrepentimos),
  hacemos el redirect en el middleware Astro (corre antes que assets).

Política de regeneración:
  Correr después de agregar un nuevo "# Pruning batch N" en _redirects.
  Output se commitea junto con el cambio del _redirects.

Idempotente. No modifica _redirects, solo lo lee.
"""
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
REDIRECTS_FILE = ROOT / 'public' / '_redirects'
OUTPUT_TS = ROOT / 'src' / 'lib' / 'pruning-redirects.ts'


def main() -> int:
    redirects = {}
    section = None
    for line in REDIRECTS_FILE.read_text(encoding='utf-8').split('\n'):
        line = line.strip()
        if line.startswith('# Pruning batch'):
            section = line
            continue
        if line.startswith('#') or not line:
            continue
        if not section:
            continue
        if not line.startswith('/'):
            continue
        parts = line.split()
        if len(parts) < 3:
            continue
        src, dst = parts[0], parts[1]
        redirects[src] = dst

    # Batches en scripts/pruning-batches/*.tsv — para podas que NO entran en
    # _redirects (CF Pages tiene un límite duro de 2000 reglas estáticas).
    # Mismo destino: el middleware. Formato: "<from>\t<to>", '#' = comentario.
    batch_dir = ROOT / 'scripts' / 'pruning-batches'
    if batch_dir.is_dir():
        for tsv in sorted(batch_dir.glob('*.tsv')):
            for line in tsv.read_text(encoding='utf-8').split('\n'):
                line = line.strip()
                if not line or line.startswith('#'):
                    continue
                parts = line.split('\t')
                if len(parts) < 2 or not parts[0].startswith('/'):
                    continue
                redirects[parts[0].strip()] = parts[1].strip()

    # ── Aplanar cadenas ──────────────────────────────────────────────────
    # A → B y B → C deja al usuario y al bot pasando por dos 301. Google los
    # sigue pero diluye el link equity en cada salto, y Bing directamente
    # corta antes. Aparecen solas cada vez que una poda nueva absorbe el
    # destino de una poda vieja (pasó con los 20 hubs de decisión: 232 de
    # golpe). Resolvemos al destino FINAL antes de emitir.
    def _final(u: str) -> str:
        seen = {u}
        while u in redirects:
            nxt = redirects[u]
            if nxt in seen:  # ciclo: cortamos y dejamos el último válido
                break
            seen.add(nxt)
            u = nxt
        return u

    # Activado 2026-08-04: la deuda de /comparar/ que impedía aplanar ya quedó
    # resuelta (audit-redirect-graph informa 0 destinos inválidos). Mantener
    # siempre activo: cada tanda nueva debe apuntar directo al destino final.
    APLANAR_CADENAS = True
    aplanadas = 0
    if APLANAR_CADENAS:
        for k in list(redirects):
            fin = _final(k)
            if fin != redirects[k]:
                redirects[k] = fin
                aplanadas += 1
    # Un redirect a sí mismo es un loop infinito en el worker.
    for k in [k for k, v in redirects.items() if k == v]:
        del redirects[k]

    # ── Targets 410 ──────────────────────────────────────────────────────
    # Un redirect cuyo destino está en gone-410/removed-ymyl-hubs es una
    # cadena 301→410 latente (Bing la castiga). Hoy están enmascaradas porque
    # las sources también figuran en la lista 410 (el worker sirve 410 directo),
    # pero cualquier tanda nueva puede romper ese overlap. Se dropean acá
    # (forense 8-07: 102 entradas).
    import re as _re
    gone = set()
    for gf in ('gone-410.ts', 'removed-ymyl-hubs.ts'):
        gp = ROOT / 'src' / 'lib' / gf
        if gp.exists():
            gone |= set(_re.findall(r"['\"](/[^'\"]*)['\"]", gp.read_text(encoding='utf-8')))
    dead = [k for k, v in redirects.items() if v in gone]
    for k in dead:
        del redirects[k]
    if dead:
        print(f'  ↳ {len(dead)} redirects dropeados por target en gone-410 (cadena 301→410 latente)')

    lines = [
        '// Generated by scripts/extract-pruning-redirects.py — DO NOT EDIT MANUALLY',
        '// Pruning batch 1+ redirects para CF Workers middleware.',
        '//',
        '// Razón: _redirects no aplica si el archivo HTML existe en dist/',
        '// (CF Workers Static Assets lo sirve antes). Middleware corre antes',
        '// que assets → soluciona sin necesidad de borrar JSONs.',
        '',
        'export const PRUNING_REDIRECTS: Record<string, string> = {',
    ]
    for src in sorted(redirects.keys()):
        # JS-safe quoting (los slugs no tienen caracteres especiales pero por las dudas)
        src_q = "'" + src.replace("'", "\\'") + "'"
        dst_q = "'" + redirects[src].replace("'", "\\'") + "'"
        lines.append(f'  {src_q}: {dst_q},')
    lines.append('};')
    lines.append('')

    OUTPUT_TS.write_text('\n'.join(lines), encoding='utf-8')
    print(f'✓ Generado: {OUTPUT_TS.relative_to(ROOT)} ({len(redirects)} entries, {aplanadas} cadenas aplanadas)')
    return 0


if __name__ == '__main__':
    import sys
    sys.exit(main())
