import type { HubData } from '../types';

export const hub: HubData = {
  slug: 'auto/importar-y-nacionalizar',
  title: 'Importar y nacionalizar un auto en Argentina: costo total',
  description: 'Compará el costo total de importar y nacionalizar un auto en Argentina frente a comprarlo acá: flete, aranceles, homologación, registro y puesta en calle.',
  silo: 'Auto',
  siloHref: '/auto',
  eyebrow: 'Importación · nacionalización · costo total',
  h1: '¿Me conviene importar y nacionalizar un auto en Argentina?',
  lede: 'El precio del vehículo es solo el comienzo. Sumá flete, seguro, aranceles, impuestos, puerto, homologación y registro para saber cuánto termina costando antes de decidir.',
  stamps: ['Estimación en dólares', 'Costo nacionalizado completo', '7 cálculos dentro'],
  resultLabel: 'Costo estimado del auto importado',
  cases: {
    title: '¿Qué decisión estás evaluando?',
    intro: 'Elegí el escenario que más se parece a tu caso. Las tasas y costos quedan editables porque cambian según el país de origen, destino, modelo y régimen.',
    items: [
      { id: 'importar', label: 'Quiero importarlo', hint: 'Costo puesto en calle', answer: 'El presupuesto real combina el auto, la logística, los tributos, la homologación y la inscripción antes de poder usarlo legalmente.', yes: ['Precio del vehículo, flete y seguro', 'Derechos e impuestos de importación', 'Puerto, despachante y traslado', 'Homologación, inspección y registro'], warn: ['La elegibilidad, seguridad, emisiones y documentación pueden impedir la nacionalización aunque el cálculo cierre.', 'No incluye financiación, seguro anual, mantenimiento ni variación cambiaria.'], plazo: 'verificas que el modelo sea importable y pedís una cotización completa por escrito.' },
      { id: 'comparar', label: 'Quiero compararlo con uno local', hint: 'Importado frente a local', answer: 'Importar conviene solo si el costo nacionalizado queda por debajo de un auto local comparable y el ahorro compensa el riesgo y la demora.', yes: ['Precio local de un modelo equivalente', 'Todos los impuestos y gastos de importación', 'Homologación y registro', 'Diferencia final en dólares'], warn: ['Compara misma versión, kilometraje, estado, garantía y equipamiento.', 'Un auto local puede incluir garantía, entrega inmediata y una reventa más sencilla.'], plazo: 'todavía puedes cancelar o renegociar si cambia el presupuesto de importación.' },
      { id: 'especial', label: 'Es un auto clásico o especial', hint: 'Primero elegibilidad', answer: 'Un régimen especial puede cambiar la importación, pero no elimina la necesidad de probar título, origen, condición y requisitos técnicos.', yes: ['Valor del vehículo y transporte', 'Tasa o exención que quieres modelar', 'Inspección, modificaciones y registro', 'Costo de restauración y almacenamiento'], warn: ['Las exenciones por antigüedad y las reglas de inscripción dependen de la jurisdicción.', 'Una demora o una restauración puede superar rápidamente el costo del flete.'], plazo: 'la autoridad confirma por escrito que ese vehículo califica.' },
    ],
  },
  inputsTitle: 'Carga tu auto importado',
  inputsIntro: 'Todos los importes están en dólares. Pon 0 cuando un impuesto o costo no aplique y usa el precio local solo para comparar.',
  fields: [
    { id: 'vehicle_price', label: 'Precio del auto', type: 'number', prefix: 'US$', value: 28000, min: 0, step: 500 },
    { id: 'vehicle_shipping', label: 'Flete hasta destino', type: 'number', prefix: 'US$', value: 2500, min: 0, step: 100 },
    { id: 'vehicle_insurance', label: 'Seguro de transporte', type: 'number', prefix: 'US$', value: 300, min: 0, step: 25 },
    { id: 'vehicle_duty_rate', label: 'Derecho de importación', type: 'number', value: 2.5, min: 0, max: 200, step: 0.1, suffix: '%' },
    { id: 'vehicle_excise_rate', label: 'Impuesto selectivo o ambiental', type: 'number', value: 0, min: 0, max: 200, step: 0.1, suffix: '%' },
    { id: 'vehicle_vat_rate', label: 'IVA o impuesto de importación', type: 'number', value: 0, min: 0, max: 100, step: 0.1, suffix: '%' },
    { id: 'port_fees', label: 'Puerto, despachante y traslado', type: 'number', prefix: 'US$', value: 1800, min: 0, step: 100 },
    { id: 'compliance_cost', label: 'Homologación, inspección y modificaciones', type: 'number', prefix: 'US$', value: 2500, min: 0, step: 100 },
    { id: 'registration_cost', label: 'Registro, título y patentes iniciales', type: 'number', prefix: 'US$', value: 900, min: 0, step: 50 },
    { id: 'local_price', label: 'Precio de un auto comparable local', type: 'number', prefix: 'US$', value: 39000, min: 0, step: 500 },
  ],
  fineprint: 'Estimación informativa. La importación, homologación, seguridad, emisiones, título y registro dependen de cada país y jurisdicción. Confirma el modelo con Aduana, la autoridad de tránsito y un despachante antes de comprar.',
  chart: { type: 'bars', title: 'Qué forma el costo nacionalizado', caption: 'Separá vehículo y logística de impuestos, puerto, homologación y registro.' },
  breakdownTitle: 'Desglose de la importación',
  breakdownIntro: 'La cuenta deja cada capa separada para que puedas auditar la cotización del despachante.',
  faq: [
    { q: '¿Qué significa nacionalizar un auto?', a: 'Es completar los trámites y pagos necesarios para que un vehículo importado pueda quedar registrado y circular legalmente en el país de destino.' },
    { q: '¿Qué costos tiene importar un auto?', a: 'Puede incluir compra, transporte, seguro, derechos, impuestos, puerto, despachante, inspección, modificaciones, homologación, título y registro.' },
    { q: '¿Puedo importar cualquier auto?', a: 'No. Las reglas de seguridad, emisiones, antigüedad, título y homologación pueden impedir la importación o hacerla inviable.' },
    { q: '¿Conviene comparar contra un auto local?', a: 'Sí. El precio local muestra el costo de oportunidad, pero compara misma versión, estado, kilometraje, garantía y equipamiento.' },
    { q: '¿El cálculo incluye seguro y mantenimiento?', a: 'No incluye el seguro anual, combustible, mantenimiento ni reparaciones. Solo considera el seguro de transporte que cargues.' },
    { q: '¿Un auto clásico paga menos?', a: 'Algunas jurisdicciones tienen tratamientos especiales, pero no son automáticos. Verifica la antigüedad, documentación y requisitos del vehículo concreto.' },
    { q: '¿Qué demoras tengo que contemplar?', a: 'Aduana, puerto, documentos faltantes, inspección, modificaciones y turnos de registro pueden extender el plazo y generar almacenaje.' },
    { q: '¿Puedo financiar un auto importado?', a: 'Depende del banco y de si acepta un vehículo sin título local o con valuación difícil. Confirma la financiación antes de inmovilizar el dinero.' },
  ],
  sources: [
    { name: 'Importación de vehículos', url: 'https://www.nhtsa.gov/importing-vehicle', publisher: 'National Highway Traffic Safety Administration' },
    { name: 'Sistema Armonizado de clasificación', url: 'https://www.wcoomd.org/en/topics/nomenclature/overview/what-is-the-harmonized-system.aspx', publisher: 'World Customs Organization' },
  ],
  replaces: [],
  lastReviewed: '2026-08-16',
  audience: 'AR',
};
