import type { HubData } from '../types';

export const hub: HubData = {
  slug: 'viajes/mudarse-al-exterior',
  title: '¿Me conviene mudarme al exterior? Calculadora de mudanza internacional',
  description: 'Compara ingreso neto, costo de vida, gastos de mudanza, meses sin ingresos y posición financiera del primer año o a cinco años.',
  silo: 'Viajes',
  siloHref: '/viajes',
  eyebrow: 'Mudanza internacional · presupuesto · decisión',
  h1: '¿Me conviene mudarme al exterior?',
  lede: 'Mudarte de país es una decisión de flujo de caja antes que de estilo de vida. Calcula cuánto te queda por mes, cuánto necesitas para llegar y si el cambio se sostiene en el tiempo.',
  stamps: ['Estimación en dólares', 'Costos del destino editables', '7 cálculos dentro'],
  resultLabel: 'Resultado financiero de la mudanza',
  cases: {
    title: '¿Qué tipo de mudanza estás pensando?',
    intro: 'Elegí el marco que más se parece a tu plan. El presupuesto queda editable porque la ciudad, la vivienda, la familia y los beneficios cambian todo.',
    items: [
      { id: 'trabajo', label: 'Me mudo por trabajo', hint: 'Flujo del primer año', answer: 'Una mudanza laboral funciona cuando el ingreso neto cubre el presupuesto mensual y los costos de transición.', yes: ['Ingreso bruto y tasa de impuestos del destino', 'Vivienda, vida diaria y salud', 'Costos que siguen en tu país', 'Meses sin ingresos y gastos iniciales'], warn: ['Compara beneficios, cobertura médica, aportes, vacaciones y bonos, no solo salario.', 'Un bono o paquete de relocalización puede cambiar completamente el primer año.'], plazo: 'la oferta y sus beneficios están documentados.' },
      { id: 'cinco-anos', label: 'Quiero comprometerme cinco años', hint: 'Posición a largo plazo', answer: 'El horizonte de cinco años muestra si el excedente mensual alcanza para recuperar la mudanza y sostener el plan.', yes: ['Excedente mensual después de todos los costos', 'Gasto inicial y reserva por meses sin ingreso', 'Posición acumulada a cinco años', 'El costo que más presiona el presupuesto'], warn: ['No es una proyección de inversiones: no incluye subas salariales, tipo de cambio ni rendimientos.', 'Un resultado positivo no confirma visa, residencia ni derecho a trabajar.'], plazo: 'puedes comparar el horizonte con tu contrato, visa y plan familiar.' },
      { id: 'jubilacion', label: 'Me mudo por jubilación', hint: 'Ingresos y salud', answer: 'Una mudanza de jubilación necesita excedente mensual durable, reserva de salud y liquidez para absorber la transición.', yes: ['Ingreso mensual confiable después de impuestos', 'Vivienda, vida diaria y cobertura médica', 'Obligaciones que quedan en origen', 'Reserva para mudanza y meses iniciales'], warn: ['Los costos médicos y de cobertura pueden aumentar con la edad; prueba un escenario más caro.', 'Confirma pensión, seguridad social, moneda y residencia con organismos oficiales.'], plazo: 'tus ingresos, cobertura y residencia están documentados.' },
    ],
  },
  inputsTitle: 'Tu presupuesto en el destino',
  inputsIntro: 'Usa importes mensuales en dólares para los costos recurrentes. La tasa de impuestos es una aproximación para planificar, no una liquidación.',
  fields: [
    { id: 'annual_gross', label: 'Ingreso bruto anual en destino', type: 'number', prefix: 'US$', value: 90000, min: 0, step: 1000 },
    { id: 'host_tax_rate', label: 'Tasa estimada de impuestos', type: 'number', value: 25, min: 0, max: 100, step: 0.5, suffix: '%' },
    { id: 'monthly_rent', label: 'Alquiler o vivienda mensual', type: 'number', prefix: 'US$', value: 2200, min: 0, step: 50 },
    { id: 'monthly_living', label: 'Comida, transporte y vida diaria', type: 'number', prefix: 'US$', value: 1600, min: 0, step: 50 },
    { id: 'monthly_health', label: 'Salud y seguro médico mensual', type: 'number', prefix: 'US$', value: 500, min: 0, step: 25 },
    { id: 'home_country_costs', label: 'Costos que mantienes en origen', type: 'number', prefix: 'US$', value: 700, min: 0, step: 25 },
    { id: 'relocation_cost', label: 'Costo único de mudanza', type: 'number', prefix: 'US$', value: 10000, min: 0, step: 250 },
    { id: 'visa_cost', label: 'Visa, gestoría y documentos', type: 'number', prefix: 'US$', value: 2500, min: 0, step: 100 },
    { id: 'income_gap_months', label: 'Meses sin ingreso normal', type: 'number', value: 2, min: 0, max: 24, step: 1 },
  ],
  fineprint: 'Estimación informativa. Inmigración, residencia fiscal, pensiones, salud y trabajo dependen de cada país. Confirma los requisitos con organismos oficiales y un profesional calificado.',
  chart: { type: 'bars', title: 'Flujo mensual en el destino', caption: 'El ingreso neto se compara con los gastos recurrentes; los costos de llegada quedan separados.' },
  breakdownTitle: 'Economía de la mudanza',
  breakdownIntro: 'Separá la capacidad mensual de la reserva que necesitas antes de subirte al avión.',
  faq: [
    { q: '¿Cuánto dinero necesito ahorrar para mudarme?', a: 'No hay un número universal. Como base, sumá los gastos únicos, los meses sin ingreso y una reserva de emergencia acorde al costo del destino.' },
    { q: '¿Tengo que comparar sueldo bruto o neto?', a: 'Compara el ingreso neto después de impuestos, aportes obligatorios, salud y cambios de beneficios. El bruto puede ocultar una diferencia grande.' },
    { q: '¿Qué costos se olvidan al mudarse?', a: 'Depósitos, vivienda temporal, pasajes, envío de pertenencias, documentos, visa, salud, colegios y cuentas que siguen en origen.' },
    { q: '¿Qué pasa con los gastos de mi país?', a: 'Hipoteca, alquiler, almacenamiento, ayuda familiar, seguros o suscripciones pueden continuar. Cargalos por separado.' },
    { q: '¿La calculadora contempla el tipo de cambio?', a: 'No. Trabaja en dólares para comparar. Probá un presupuesto más alto si tus ingresos y gastos están en monedas distintas.' },
    { q: '¿Un excedente mensual positivo alcanza para mudarme?', a: 'No por sí solo. También necesitas visa, derecho a trabajar, cobertura médica, ahorro de emergencia y un ingreso confiable.' },
    { q: '¿Cómo la uso si me jubilo?', a: 'Carga ingresos confiables después de impuestos y somete a estrés salud, vivienda y moneda. No cuentes rendimientos inciertos como ingreso mensual.' },
    { q: '¿Cuándo conviene mirar el caso de cinco años?', a: 'Cuando la decisión implica un contrato, visa o compromiso familiar de varios años. Muestra si recuperás la inversión inicial, no si la mudanza es legal.' },
  ],
  sources: [
    { name: 'Costos de vida por ciudad', url: 'https://www.numbeo.com/cost-of-living/', publisher: 'Numbeo' },
    { name: 'Información para viajar y vivir en el exterior', url: 'https://www.argentina.gob.ar/interior/migraciones', publisher: 'Gobierno de la República Argentina' },
  ],
  replaces: [],
  lastReviewed: '2026-08-09',
  audience: 'AR',
};
