import type { HubData } from '../types';

export const hub: HubData = {
  slug: 'impuestos/residencia-fiscal-nomadas-digitales',
  title: 'Residencia fiscal para nómadas digitales | Días y países',
  description: 'Organiza tus días, compara umbrales de residencia fiscal y estima la diferencia de impuestos sobre ingresos del exterior antes de consultar a un profesional.',
  silo: 'Impuestos',
  siloHref: '/impuestos',
  eyebrow: 'Nómadas digitales · días · residencia fiscal',
  h1: 'Residencia fiscal para nómadas digitales',
  lede: 'La cantidad de días importa, pero no es lo único. Ordena tus viajes, prueba el umbral que estás investigando y mira cómo cambia la cuenta si dos países reclaman tu residencia.',
  stamps: ['Pantalla de planificación', 'Umbrales editables', '7 cálculos dentro'],
  resultLabel: 'Resultado de tu prueba de residencia',
  cases: {
    title: '¿Qué quieres revisar?',
    intro: 'Elegí la prueba que más se parece a tu situación. El resultado es una lista de control para reunir documentación, no una conclusión legal.',
    items: [
      { id: 'nomada', label: 'Soy nómada digital', hint: 'Días y países', answer: 'Un nómada digital puede tener obligaciones en más de un país: la prueba de días es el primer filtro, no el análisis completo.', yes: ['Días del año actual y de años anteriores', 'País donde está tu vivienda y centro de vida', 'Ingreso del exterior y tasas orientativas', 'Tratados y documentación a revisar'], warn: ['La visa de nómada digital no determina por sí sola la residencia fiscal.', 'Familia, vivienda permanente, centro de intereses económicos y tratados pueden pesar tanto como los días.'], plazo: 'tienes un registro de entradas, salidas, contratos, vivienda e ingresos.' },
      { id: 'diferencia', label: 'Quiero comparar dos países', hint: 'Brecha de impuesto', answer: 'Comparar tasas puede orientar, pero la residencia y la base imponible se definen con las reglas completas de cada país.', yes: ['Ingreso que quieres comparar', 'Tasa aproximada del país de origen', 'Tasa aproximada del destino', 'Brecha orientativa antes de deducciones y tratados'], warn: ['Una tasa menor no implica menor impuesto final: importan base imponible, aportes, deducciones, fuente y moneda.', 'No cierres una residencia, empresa o cuenta bancaria solo por esta diferencia.'], plazo: 'un asesor confirma la base imponible, el tratado y las obligaciones de ambos países.' },
      { id: 'eeuu', label: 'Estoy evaluando Estados Unidos', hint: 'Presencia sustancial', answer: 'La prueba estadounidense combina días del año actual con una fracción de los dos años anteriores, además de excepciones.', yes: ['Días del año actual', 'Días de los dos años anteriores', 'Umbral del año actual y ponderado', 'Excepciones y registros de viaje'], warn: ['La prueba del IRS tiene excepciones y formularios. Pasar esta pantalla no define por sí solo tu presentación.', 'Concilia los días con pasaporte, tickets, visas y registros de viaje.'], plazo: 'revisas la prueba oficial y sus excepciones antes de presentar o cambiar retenciones.' },
    ],
  },
  inputsTitle: 'Tus días e ingresos',
  inputsIntro: 'Carga días desde registros confiables. Los umbrales son editables para modelar la regla oficial que estés investigando.',
  fields: [
    { id: 'current_days', label: 'Días en el país este año', type: 'number', value: 120, min: 0, max: 366, step: 1 },
    { id: 'previous_days', label: 'Días en el año anterior', type: 'number', value: 90, min: 0, max: 366, step: 1 },
    { id: 'older_days', label: 'Días hace dos años', type: 'number', value: 60, min: 0, max: 366, step: 1 },
    { id: 'current_minimum_days', label: 'Mínimo de días del año actual', type: 'number', value: 31, min: 0, max: 366, step: 1 },
    { id: 'residency_threshold', label: 'Umbral de presencia ponderada', type: 'number', value: 183, min: 0, max: 1000, step: 1 },
    { id: 'foreign_days', label: 'Días completos fuera del país', type: 'number', value: 280, min: 0, max: 366, step: 1 },
    { id: 'foreign_threshold', label: 'Umbral de presencia física', type: 'number', value: 330, min: 0, max: 366, step: 1 },
    { id: 'foreign_income', label: 'Ingreso del exterior', type: 'number', prefix: 'US$', value: 80000, min: 0, step: 1000 },
    { id: 'home_tax_rate', label: 'Tasa estimada de origen', type: 'number', value: 30, min: 0, max: 100, step: 0.5, suffix: '%' },
    { id: 'host_tax_rate', label: 'Tasa estimada de destino', type: 'number', value: 20, min: 0, max: 100, step: 0.5, suffix: '%' },
  ],
  fineprint: 'Estimación informativa. La residencia fiscal, los tratados, la fuente del ingreso, los aportes y las exclusiones dependen de tus circunstancias y de las reglas oficiales. Guarda un registro de viajes y consulta a un profesional antes de presentar o cambiar tu situación.',
  chart: { type: 'bars', title: 'Señales de presencia', caption: 'Compara días del año actual, presencia ponderada y días completos fuera del país.' },
  breakdownTitle: 'Señales para revisar',
  breakdownIntro: 'Cada fila funciona como una lista de documentación. Cambiá los umbrales para modelar la regla oficial que corresponda.',
  faq: [
    { q: '¿Qué es la residencia fiscal?', a: 'Es el estatus que un país asigna según sus reglas y que puede determinar dónde declarás ingresos. No siempre coincide con ciudadanía, visa o domicilio.' },
    { q: '¿La visa de nómada digital me hace residente fiscal?', a: 'No necesariamente. La visa migratoria y la residencia fiscal son análisis distintos, aunque la visa puede afectar tus días, derecho a trabajar y documentación.' },
    { q: '¿Qué es la regla de los 183 días?', a: 'Muchos países usan 183 días como una señal o umbral, pero no todos cuentan los días igual ni aplican la regla de forma aislada.' },
    { q: '¿Cómo calcula Estados Unidos la presencia sustancial?', a: 'En general combina todos los días del año actual, un tercio del año anterior y un sexto del año previo, con un mínimo de días en el año actual y excepciones.' },
    { q: '¿Puedo ser residente fiscal de dos países?', a: 'Sí, las reglas internas pueden superponerse. Un tratado puede tener reglas de desempate basadas en vivienda, centro de intereses y permanencia habitual.' },
    { q: '¿La calculadora calcula mis impuestos?', a: 'No. Ordena días y muestra una diferencia orientativa de tasas sobre el ingreso cargado. No calcula deducciones, aportes, créditos, tratados ni la base imponible.' },
    { q: '¿Qué documentación debería guardar?', a: 'Pasaportes, tickets, registros fronterizos, contratos de vivienda, servicios, visas, calendarios, empleo, facturas y un registro contemporáneo de viajes.' },
    { q: '¿Cuándo tengo que consultar a un profesional?', a: 'Antes de cambiar residencia, cerrar una empresa, reclamar una exclusión, modificar retenciones o presentar una declaración con dos países involucrados.' },
  ],
  sources: [
    { name: 'Prueba de presencia sustancial', url: 'https://www.irs.gov/individuals/international-taxpayers/substantial-presence-test', publisher: 'Internal Revenue Service' },
    { name: 'Prueba de presencia física', url: 'https://www.irs.gov/individuals/international-taxpayers/foreign-earned-income-exclusion-physical-presence-test', publisher: 'Internal Revenue Service' },
    { name: 'Modelo de convenio tributario', url: 'https://www.oecd.org/content/dam/oecd/en/publications/reports/2017/12/model-tax-convention-on-income-and-on-capital-condensed-version-2017_g1g8769b/mtc_cond-2017-en.pdf', publisher: 'OECD' },
  ],
  replaces: [],
  lastReviewed: '2026-08-09',
  audience: 'AR',
};
